// Rangen bij de Nederlandse krijgsmacht (bron: brochure "De rang-
// onderscheidingstekens van de krijgsmacht", Ministerie van Defensie, 2016),
// de politie en de brandweer (bron: Wikipedia).
export type Rang = {
  naam: string
  // rangcluster of functiegroep
  cluster: string
  // afwijkende aanspreektitel (alleen krijgsmacht) of onderscheidingsteken
  detail?: string
}

export type Onderdeel = {
  id: string
  naam: string
  kort: string
  mark: string
  accent: string
  intro: string
  // van hoog naar laag
  rangen: Rang[]
  bron: { label: string; url?: string }
}

export const ONDERDELEN: Onderdeel[] = [
  {
    id: 'marine',
    naam: 'Koninklijke Marine (vloot)',
    kort: 'Marine',
    mark: 'KM',
    accent: '#1f4e79',
    intro: 'Bij de marine heten de clusters: vlag- en opperofficieren, hoofdofficieren, subalterne officieren, onderofficieren (waartoe ook de korporaal behoort) en manschappen.',
    rangen: [
      { naam: 'Luitenant-admiraal', cluster: 'Vlagofficieren', detail: 'aanspreektitel: admiraal' },
      { naam: 'Vice-admiraal', cluster: 'Vlagofficieren', detail: 'aanspreektitel: admiraal' },
      { naam: 'Schout-bij-nacht', cluster: 'Vlagofficieren' },
      { naam: 'Commandeur', cluster: 'Vlagofficieren' },
      { naam: 'Kapitein-ter-zee', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: kolonel' },
      { naam: 'Kapitein-luitenant-ter-zee', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: overste' },
      { naam: 'Luitenant-ter-zee der 1e klasse', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: mijnheer/mevrouw' },
      { naam: 'Luitenant-ter-zee der 2e klasse oudste categorie', cluster: 'Subalterne officieren', detail: 'aanspreektitel: mijnheer/mevrouw' },
      { naam: 'Luitenant-ter-zee der 2e klasse', cluster: 'Subalterne officieren', detail: 'aanspreektitel: mijnheer/mevrouw' },
      { naam: 'Luitenant-ter-zee der 3e klasse', cluster: 'Subalterne officieren', detail: 'aanspreektitel: mijnheer/mevrouw' },
      { naam: 'Adjudant-onderofficier', cluster: 'Onderofficieren', detail: 'aanspreektitel: adjudant (nautische dienst: opperschipper)' },
      { naam: 'Sergeant-majoor', cluster: 'Onderofficieren', detail: 'aanspreektitel: majoor (nautische dienst: schipper)' },
      { naam: 'Sergeant', cluster: 'Onderofficieren', detail: 'nautische dienst: bootsman' },
      { naam: 'Korporaal', cluster: 'Onderofficieren', detail: 'nautische dienst: kwartiermeester' },
      { naam: 'Matroos der 1e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: matroos' },
      { naam: 'Matroos der 2e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: matroos' },
      { naam: 'Matroos der 3e klasse', cluster: 'Manschappen' },
    ],
    bron: { label: 'Brochure Ministerie van Defensie (2016)' },
  },
  {
    id: 'mariniers',
    naam: 'Korps Mariniers',
    kort: 'Mariniers',
    mark: 'MRN',
    accent: '#14532d',
    intro: 'De mariniers vallen onder de Koninklijke Marine maar voeren landmacht-achtige rangen "der mariniers". Bij onderofficieren en manschappen zit rood om de chevrons. (Van de mariniersrangen zijn geen vrije insigne-afbeeldingen beschikbaar.)',
    rangen: [
      { naam: 'Generaal der mariniers', cluster: 'Opperofficieren' },
      { naam: 'Luitenant-generaal der mariniers', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Generaal-majoor der mariniers', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Brigadegeneraal der mariniers', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Kolonel der mariniers', cluster: 'Hoofdofficieren' },
      { naam: 'Luitenant-kolonel der mariniers', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: overste' },
      { naam: 'Majoor der mariniers', cluster: 'Hoofdofficieren' },
      { naam: 'Kapitein der mariniers', cluster: 'Subalterne officieren' },
      { naam: 'Eerste luitenant der mariniers', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Tweede luitenant der mariniers', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Adjudant-onderofficier van de mariniers', cluster: 'Onderofficieren', detail: 'aanspreektitel: adjudant' },
      { naam: 'Sergeant-majoor van de mariniers', cluster: 'Onderofficieren', detail: 'aanspreektitel: majoor' },
      { naam: 'Sergeant van de mariniers', cluster: 'Onderofficieren' },
      { naam: 'Korporaal van de mariniers', cluster: 'Onderofficieren' },
      { naam: 'Marinier der 1e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: marinier' },
      { naam: 'Marinier der 2e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: marinier' },
      { naam: 'Marinier der 3e klasse', cluster: 'Manschappen' },
    ],
    bron: { label: 'Brochure Ministerie van Defensie (2016)' },
  },
  {
    id: 'landmacht',
    naam: 'Koninklijke Landmacht',
    kort: 'Landmacht',
    mark: 'KL',
    accent: '#4d5d2a',
    intro: 'Bij cavalerie en militaire administratie zijn de tekens van korporaal t/m sergeant-majoor/opperwachtmeester in zilver uitgevoerd. Cavalerie gebruikt eigen rangnamen: ritmeester (kapitein), kornet (vaandrig), wachtmeester (sergeant).',
    rangen: [
      { naam: 'Generaal', cluster: 'Opperofficieren' },
      { naam: 'Luitenant-generaal', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Generaal-majoor', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Brigadegeneraal', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Kolonel', cluster: 'Hoofdofficieren' },
      { naam: 'Luitenant-kolonel', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: overste' },
      { naam: 'Majoor', cluster: 'Hoofdofficieren' },
      { naam: 'Kapitein / ritmeester', cluster: 'Subalterne officieren' },
      { naam: 'Eerste luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Tweede luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Vaandrig / kornet', cluster: 'Subalterne officieren', detail: 'officier in opleiding' },
      { naam: 'Adjudant-onderofficier', cluster: 'Onderofficieren', detail: 'aanspreektitel: adjudant' },
      { naam: 'Sergeant-majoor / opperwachtmeester', cluster: 'Onderofficieren' },
      { naam: 'Sergeant der 1e klasse / wachtmeester der 1e klasse', cluster: 'Onderofficieren', detail: 'aanspreektitel: sergeant/wachtmeester' },
      { naam: 'Sergeant / wachtmeester', cluster: 'Onderofficieren' },
      { naam: 'Korporaal der 1e klasse', cluster: 'Korporaals', detail: 'aanspreektitel: korporaal' },
      { naam: 'Korporaal', cluster: 'Korporaals' },
      { naam: 'Soldaat der 1e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: soldaat (of grenadier, jager, fuselier, commando, huzaar, kanonnier…)' },
      { naam: 'Soldaat der 2e klasse', cluster: 'Manschappen' },
      { naam: 'Soldaat der 3e klasse', cluster: 'Manschappen' },
    ],
    bron: { label: 'Brochure Ministerie van Defensie (2016)' },
  },
  {
    id: 'luchtmacht',
    naam: 'Koninklijke Luchtmacht',
    kort: 'Luchtmacht',
    mark: 'KLu',
    accent: '#2b5f8f',
    intro: 'De luchtmacht volgt de landmacht-indeling, met de commodore als eigen rang op het niveau van brigadegeneraal.',
    rangen: [
      { naam: 'Generaal', cluster: 'Opperofficieren' },
      { naam: 'Luitenant-generaal', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Generaal-majoor', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Commodore', cluster: 'Opperofficieren' },
      { naam: 'Kolonel', cluster: 'Hoofdofficieren' },
      { naam: 'Luitenant-kolonel', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: overste' },
      { naam: 'Majoor', cluster: 'Hoofdofficieren' },
      { naam: 'Kapitein', cluster: 'Subalterne officieren' },
      { naam: 'Eerste luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Tweede luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Vaandrig', cluster: 'Subalterne officieren', detail: 'officier in opleiding' },
      { naam: 'Adjudant-onderofficier', cluster: 'Onderofficieren', detail: 'aanspreektitel: adjudant' },
      { naam: 'Sergeant-majoor', cluster: 'Onderofficieren' },
      { naam: 'Sergeant der 1e klasse', cluster: 'Onderofficieren', detail: 'aanspreektitel: sergeant' },
      { naam: 'Sergeant', cluster: 'Onderofficieren' },
      { naam: 'Korporaal der 1e klasse', cluster: 'Korporaals', detail: 'aanspreektitel: korporaal' },
      { naam: 'Korporaal', cluster: 'Korporaals' },
      { naam: 'Soldaat der 1e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: soldaat' },
      { naam: 'Soldaat der 2e klasse', cluster: 'Manschappen' },
      { naam: 'Soldaat der 3e klasse', cluster: 'Manschappen' },
    ],
    bron: { label: 'Brochure Ministerie van Defensie (2016)' },
  },
  {
    id: 'marechaussee',
    naam: 'Koninklijke Marechaussee',
    kort: 'Marechaussee',
    mark: 'KMar',
    accent: '#27427c',
    intro: 'De marechaussee gebruikt cavalerierangen (wachtmeester, kornet) en kent als manschappenrang de marechaussee der 1e t/m 4e klasse.',
    rangen: [
      { naam: 'Luitenant-generaal', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Generaal-majoor', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Brigadegeneraal', cluster: 'Opperofficieren', detail: 'aanspreektitel: generaal' },
      { naam: 'Kolonel', cluster: 'Hoofdofficieren' },
      { naam: 'Luitenant-kolonel', cluster: 'Hoofdofficieren', detail: 'aanspreektitel: overste' },
      { naam: 'Majoor', cluster: 'Hoofdofficieren' },
      { naam: 'Kapitein', cluster: 'Subalterne officieren' },
      { naam: 'Eerste luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Tweede luitenant', cluster: 'Subalterne officieren', detail: 'aanspreektitel: luitenant' },
      { naam: 'Kornet', cluster: 'Subalterne officieren', detail: 'officier in opleiding' },
      { naam: 'Adjudant-onderofficier', cluster: 'Onderofficieren', detail: 'aanspreektitel: adjudant' },
      { naam: 'Opperwachtmeester', cluster: 'Onderofficieren' },
      { naam: 'Wachtmeester der 1e klasse', cluster: 'Onderofficieren', detail: 'aanspreektitel: wachtmeester' },
      { naam: 'Wachtmeester', cluster: 'Onderofficieren' },
      { naam: 'Marechaussee der 1e klasse', cluster: 'Manschappen', detail: 'aanspreektitel: marechaussee' },
      { naam: 'Marechaussee der 2e klasse', cluster: 'Manschappen' },
      { naam: 'Marechaussee der 3e klasse', cluster: 'Manschappen' },
      { naam: 'Marechaussee der 4e klasse', cluster: 'Manschappen' },
    ],
    bron: { label: 'Brochure Ministerie van Defensie (2016)' },
  },
  {
    id: 'politie',
    naam: 'Nationale Politie',
    kort: 'Politie',
    mark: 'POL',
    accent: '#1e3a6e',
    intro: 'De politierangen sinds de vorming van de Nationale Politie (2013). De rang adjudant verdween bij de reorganisatie van 1993; de eerste hoofdcommissaris (korpschef) kwam er in 2013 bij.',
    rangen: [
      { naam: 'Eerste hoofdcommissaris', cluster: 'Leiding', detail: 'teken: vier sterren, tak met zwaarden en kroon — de korpschef' },
      { naam: 'Hoofdcommissaris', cluster: 'Leiding', detail: 'teken: tak met zwaarden en kroon' },
      { naam: 'Commissaris', cluster: 'Leiding', detail: 'teken: tak en kroon' },
      { naam: 'Hoofdinspecteur', cluster: 'Officieren', detail: 'teken: balk en kroon' },
      { naam: 'Inspecteur', cluster: 'Officieren', detail: 'teken: kroon' },
      { naam: 'Brigadier', cluster: 'Officieren', detail: 'teken: lauwerkrans' },
      { naam: 'Hoofdagent', cluster: 'Uitvoerend', detail: 'teken: vier strepen' },
      { naam: 'Agent', cluster: 'Uitvoerend', detail: 'teken: drie strepen' },
      { naam: 'Surveillant', cluster: 'Uitvoerend', detail: 'teken: twee strepen' },
      { naam: 'Aspirant', cluster: 'Uitvoerend', detail: 'teken: één streep — in opleiding' },
    ],
    bron: { label: 'Wikipedia: Lijst van rangen bij de Nederlandse politie', url: 'https://nl.wikipedia.org/wiki/Lijst_van_rangen_bij_de_Nederlandse_politie' },
  },
  {
    id: 'brandweer',
    naam: 'Brandweer',
    kort: 'Brandweer',
    mark: 'BRW',
    accent: '#a03030',
    intro: 'Sinds 2011 wordt brandweerpersoneel niet meer in rang maar in functie aangesteld; de "rangen" horen bij functies. Onderscheidingstekens staan op epauletten (rood, oranje en geel voor oplopende repressieve functies).',
    rangen: [
      { naam: 'Hoofdcommandeur', cluster: 'Officieren', detail: 'hoogste functie' },
      { naam: 'Adjunct-hoofdcommandeur', cluster: 'Officieren' },
      { naam: 'Commandeur', cluster: 'Officieren' },
      { naam: 'Hoofdbrandmeester', cluster: 'Officieren' },
      { naam: 'Brandmeester', cluster: 'Onderofficieren', detail: 'o.a. bevelvoerder' },
      { naam: 'Hoofdbrandwacht', cluster: 'Manschappen' },
      { naam: 'Brandwacht', cluster: 'Manschappen' },
      { naam: 'Aspirant', cluster: 'Manschappen', detail: 'in opleiding' },
    ],
    bron: { label: 'Wikipedia: Lijst van rangen bij de Nederlandse brandweer', url: 'https://nl.wikipedia.org/wiki/Lijst_van_rangen_bij_de_Nederlandse_brandweer' },
  },
]
