// Gegenereerd: rangonderscheidingstekens per onderdeel en rang
// (afbeeldingen via Wikipedia / Wikimedia Commons, in public/rangen).
export const INSIGNES: Record<string, string> = {
  'brandweer|Adjunct-hoofdcommandeur': 'brandweer--adjunct-hoofdcommandeur.png',
  'brandweer|Aspirant': 'brandweer--aspirant.png',
  'brandweer|Brandmeester': 'brandweer--brandmeester.png',
  'brandweer|Brandwacht': 'brandweer--brandwacht.png',
  'brandweer|Commandeur': 'brandweer--commandeur.png',
  'brandweer|Hoofdbrandmeester': 'brandweer--hoofdbrandmeester.png',
  'brandweer|Hoofdbrandwacht': 'brandweer--hoofdbrandwacht.png',
  'brandweer|Hoofdcommandeur': 'brandweer--hoofdcommandeur.png',
  'landmacht|Adjudant-onderofficier': 'landmacht--adjudant-onderofficier.png',
  'landmacht|Brigadegeneraal': 'landmacht--brigadegeneraal.png',
  'landmacht|Eerste luitenant': 'landmacht--eerste-luitenant.png',
  'landmacht|Generaal': 'landmacht--generaal.png',
  'landmacht|Generaal-majoor': 'landmacht--generaal-majoor.png',
  'landmacht|Kapitein / ritmeester': 'landmacht--kapitein-ritmeester.png',
  'landmacht|Kolonel': 'landmacht--kolonel.png',
  'landmacht|Korporaal': 'landmacht--korporaal.png',
  'landmacht|Korporaal der 1e klasse': 'landmacht--korporaal-der-1e-klasse.png',
  'landmacht|Luitenant-generaal': 'landmacht--luitenant-generaal.png',
  'landmacht|Luitenant-kolonel': 'landmacht--luitenant-kolonel.png',
  'landmacht|Majoor': 'landmacht--majoor.png',
  'landmacht|Sergeant / wachtmeester': 'landmacht--sergeant-wachtmeester.png',
  'landmacht|Sergeant der 1e klasse / wachtmeester der 1e klasse': 'landmacht--sergeant-der-1e-klasse-wachtmeester-der-1e-klass.png',
  'landmacht|Sergeant-majoor / opperwachtmeester': 'landmacht--sergeant-majoor-opperwachtmeester.png',
  'landmacht|Soldaat der 1e klasse': 'landmacht--soldaat-der-1e-klasse.png',
  'landmacht|Soldaat der 2e klasse': 'landmacht--soldaat-der-2e-klasse.png',
  'landmacht|Tweede luitenant': 'landmacht--tweede-luitenant.png',
  'landmacht|Vaandrig / kornet': 'landmacht--vaandrig-kornet.png',
  'luchtmacht|Adjudant-onderofficier': 'luchtmacht--adjudant-onderofficier.png',
  'luchtmacht|Commodore': 'luchtmacht--commodore.png',
  'luchtmacht|Eerste luitenant': 'luchtmacht--eerste-luitenant.png',
  'luchtmacht|Generaal': 'luchtmacht--generaal.png',
  'luchtmacht|Generaal-majoor': 'luchtmacht--generaal-majoor.png',
  'luchtmacht|Kapitein': 'luchtmacht--kapitein.png',
  'luchtmacht|Kolonel': 'luchtmacht--kolonel.png',
  'luchtmacht|Korporaal': 'luchtmacht--korporaal.png',
  'luchtmacht|Korporaal der 1e klasse': 'luchtmacht--korporaal-der-1e-klasse.png',
  'luchtmacht|Luitenant-generaal': 'luchtmacht--luitenant-generaal.png',
  'luchtmacht|Luitenant-kolonel': 'luchtmacht--luitenant-kolonel.png',
  'luchtmacht|Majoor': 'luchtmacht--majoor.png',
  'luchtmacht|Sergeant': 'luchtmacht--sergeant.png',
  'luchtmacht|Sergeant der 1e klasse': 'luchtmacht--sergeant-der-1e-klasse.png',
  'luchtmacht|Sergeant-majoor': 'luchtmacht--sergeant-majoor.png',
  'luchtmacht|Soldaat der 1e klasse': 'luchtmacht--soldaat-der-1e-klasse.png',
  'luchtmacht|Soldaat der 2e klasse': 'luchtmacht--soldaat-der-2e-klasse.png',
  'luchtmacht|Soldaat der 3e klasse': 'luchtmacht--soldaat-der-3e-klasse.png',
  'luchtmacht|Tweede luitenant': 'luchtmacht--tweede-luitenant.png',
  'luchtmacht|Vaandrig': 'luchtmacht--vaandrig.png',
  'marechaussee|Adjudant-onderofficier': 'marechaussee--adjudant-onderofficier.png',
  'marechaussee|Brigadegeneraal': 'marechaussee--brigadegeneraal.png',
  'marechaussee|Eerste luitenant': 'marechaussee--eerste-luitenant.png',
  'marechaussee|Generaal-majoor': 'marechaussee--generaal-majoor.png',
  'marechaussee|Kapitein': 'marechaussee--kapitein.png',
  'marechaussee|Kolonel': 'marechaussee--kolonel.png',
  'marechaussee|Luitenant-generaal': 'marechaussee--luitenant-generaal.png',
  'marechaussee|Luitenant-kolonel': 'marechaussee--luitenant-kolonel.png',
  'marechaussee|Majoor': 'marechaussee--majoor.png',
  'marechaussee|Marechaussee der 1e klasse': 'marechaussee--marechaussee-der-1e-klasse.png',
  'marechaussee|Marechaussee der 2e klasse': 'marechaussee--marechaussee-der-2e-klasse.png',
  'marechaussee|Marechaussee der 3e klasse': 'marechaussee--marechaussee-der-3e-klasse.png',
  'marechaussee|Marechaussee der 4e klasse': 'marechaussee--marechaussee-der-4e-klasse.png',
  'marechaussee|Opperwachtmeester': 'marechaussee--opperwachtmeester.png',
  'marechaussee|Tweede luitenant': 'marechaussee--tweede-luitenant.png',
  'marechaussee|Wachtmeester': 'marechaussee--wachtmeester.png',
  'marechaussee|Wachtmeester der 1e klasse': 'marechaussee--wachtmeester-der-1e-klasse.png',
  'marine|Adjudant-onderofficier': 'marine--adjudant-onderofficier.png',
  'marine|Commandeur': 'marine--commandeur.png',
  'marine|Kapitein-luitenant-ter-zee': 'marine--kapitein-luitenant-ter-zee.png',
  'marine|Kapitein-ter-zee': 'marine--kapitein-ter-zee.png',
  'marine|Korporaal': 'marine--korporaal.png',
  'marine|Luitenant-admiraal': 'marine--luitenant-admiraal.png',
  'marine|Luitenant-ter-zee der 1e klasse': 'marine--luitenant-ter-zee-der-1e-klasse.png',
  'marine|Luitenant-ter-zee der 2e klasse': 'marine--luitenant-ter-zee-der-2e-klasse.png',
  'marine|Luitenant-ter-zee der 2e klasse oudste categorie': 'marine--luitenant-ter-zee-der-2e-klasse-oudste-categorie.png',
  'marine|Luitenant-ter-zee der 3e klasse': 'marine--luitenant-ter-zee-der-3e-klasse.png',
  'marine|Matroos der 1e klasse': 'marine--matroos-der-1e-klasse.png',
  'marine|Matroos der 2e klasse': 'marine--matroos-der-2e-klasse.png',
  'marine|Matroos der 3e klasse': 'marine--matroos-der-3e-klasse.png',
  'marine|Schout-bij-nacht': 'marine--schout-bij-nacht.png',
  'marine|Sergeant': 'marine--sergeant.png',
  'marine|Sergeant-majoor': 'marine--sergeant-majoor.png',
  'marine|Vice-admiraal': 'marine--vice-admiraal.png',
  'politie|Agent': 'politie--agent.png',
  'politie|Aspirant': 'politie--aspirant.png',
  'politie|Brigadier': 'politie--brigadier.png',
  'politie|Commissaris': 'politie--commissaris.png',
  'politie|Eerste hoofdcommissaris': 'politie--eerste-hoofdcommissaris.png',
  'politie|Hoofdagent': 'politie--hoofdagent.png',
  'politie|Hoofdcommissaris': 'politie--hoofdcommissaris.png',
  'politie|Hoofdinspecteur': 'politie--hoofdinspecteur.png',
  'politie|Inspecteur': 'politie--inspecteur.png',
  'politie|Surveillant': 'politie--surveillant.png',
}
