// Alle 195 landen (VN-lidstaten + enkele), met Nederlandse naam en hoofdstad,
// ISO-alpha2 (voor de vlag-emoji) en geografisch middelpunt (voor de wereldkaart).

export type Land = {
  iso2: string
  naam: string
  hoofdstad: string
  werelddeel: string
  lat: number
  lon: number
}

export const LANDEN: Land[] = [
  { iso2: 'AF', naam: 'Afghanistan', hoofdstad: 'Kaboel', werelddeel: 'Azië', lat: 33.9, lon: 67.7 },
  { iso2: 'AL', naam: 'Albanië', hoofdstad: 'Tirana', werelddeel: 'Europa', lat: 41.2, lon: 20.2 },
  { iso2: 'DZ', naam: 'Algerije', hoofdstad: 'Algiers', werelddeel: 'Afrika', lat: 28, lon: 2.6 },
  { iso2: 'AD', naam: 'Andorra', hoofdstad: 'Andorra la Vella', werelddeel: 'Europa', lat: 42.5, lon: 1.6 },
  { iso2: 'AO', naam: 'Angola', hoofdstad: 'Luanda', werelddeel: 'Afrika', lat: -11.2, lon: 17.9 },
  { iso2: 'AG', naam: 'Antigua en Barbuda', hoofdstad: 'Saint John\'s', werelddeel: 'Noord-Amerika', lat: 17.1, lon: -61.8 },
  { iso2: 'AR', naam: 'Argentinië', hoofdstad: 'Buenos Aires', werelddeel: 'Zuid-Amerika', lat: -38.4, lon: -63.6 },
  { iso2: 'AM', naam: 'Armenië', hoofdstad: 'Jerevan', werelddeel: 'Azië', lat: 40.1, lon: 45 },
  { iso2: 'AU', naam: 'Australië', hoofdstad: 'Canberra', werelddeel: 'Oceanië', lat: -25.3, lon: 133.8 },
  { iso2: 'AZ', naam: 'Azerbeidzjan', hoofdstad: 'Bakoe', werelddeel: 'Azië', lat: 40.1, lon: 47.6 },
  { iso2: 'BS', naam: 'Bahama\'s', hoofdstad: 'Nassau', werelddeel: 'Noord-Amerika', lat: 25, lon: -77.4 },
  { iso2: 'BH', naam: 'Bahrein', hoofdstad: 'Manama', werelddeel: 'Azië', lat: 26, lon: 50.6 },
  { iso2: 'BD', naam: 'Bangladesh', hoofdstad: 'Dhaka', werelddeel: 'Azië', lat: 23.7, lon: 90.4 },
  { iso2: 'BB', naam: 'Barbados', hoofdstad: 'Bridgetown', werelddeel: 'Noord-Amerika', lat: 13.2, lon: -59.5 },
  { iso2: 'BE', naam: 'België', hoofdstad: 'Brussel', werelddeel: 'Europa', lat: 50.5, lon: 4.5 },
  { iso2: 'BZ', naam: 'Belize', hoofdstad: 'Belmopan', werelddeel: 'Noord-Amerika', lat: 17.2, lon: -88.5 },
  { iso2: 'BJ', naam: 'Benin', hoofdstad: 'Porto-Novo', werelddeel: 'Afrika', lat: 9.3, lon: 2.3 },
  { iso2: 'BT', naam: 'Bhutan', hoofdstad: 'Thimphu', werelddeel: 'Azië', lat: 27.5, lon: 90.4 },
  { iso2: 'BO', naam: 'Bolivia', hoofdstad: 'Sucre', werelddeel: 'Zuid-Amerika', lat: -16.3, lon: -63.6 },
  { iso2: 'BA', naam: 'Bosnië en Herzegovina', hoofdstad: 'Sarajevo', werelddeel: 'Europa', lat: 43.9, lon: 17.7 },
  { iso2: 'BW', naam: 'Botswana', hoofdstad: 'Gaborone', werelddeel: 'Afrika', lat: -22.3, lon: 24.7 },
  { iso2: 'BR', naam: 'Brazilië', hoofdstad: 'Brasilia', werelddeel: 'Zuid-Amerika', lat: -14.2, lon: -51.9 },
  { iso2: 'BN', naam: 'Brunei', hoofdstad: 'Bandar Seri Begawan', werelddeel: 'Azië', lat: 4.5, lon: 114.7 },
  { iso2: 'BG', naam: 'Bulgarije', hoofdstad: 'Sofia', werelddeel: 'Europa', lat: 42.7, lon: 25.5 },
  { iso2: 'BF', naam: 'Burkina Faso', hoofdstad: 'Ouagadougou', werelddeel: 'Afrika', lat: 12.2, lon: -1.6 },
  { iso2: 'BI', naam: 'Burundi', hoofdstad: 'Gitega', werelddeel: 'Afrika', lat: -3.4, lon: 29.9 },
  { iso2: 'KH', naam: 'Cambodja', hoofdstad: 'Phnom Penh', werelddeel: 'Azië', lat: 12.6, lon: 104.9 },
  { iso2: 'CA', naam: 'Canada', hoofdstad: 'Ottawa', werelddeel: 'Noord-Amerika', lat: 56.1, lon: -106.3 },
  { iso2: 'CF', naam: 'Centraal-Afrikaanse Republiek', hoofdstad: 'Bangui', werelddeel: 'Afrika', lat: 6.6, lon: 20.9 },
  { iso2: 'CL', naam: 'Chili', hoofdstad: 'Santiago', werelddeel: 'Zuid-Amerika', lat: -35.7, lon: -71.5 },
  { iso2: 'CN', naam: 'China', hoofdstad: 'Peking', werelddeel: 'Azië', lat: 35.9, lon: 104.2 },
  { iso2: 'CO', naam: 'Colombia', hoofdstad: 'Bogota', werelddeel: 'Zuid-Amerika', lat: 4.6, lon: -74.3 },
  { iso2: 'KM', naam: 'Comoren', hoofdstad: 'Moroni', werelddeel: 'Afrika', lat: -11.6, lon: 43.3 },
  { iso2: 'CG', naam: 'Congo-Brazzaville', hoofdstad: 'Brazzaville', werelddeel: 'Afrika', lat: -0.2, lon: 15.8 },
  { iso2: 'CD', naam: 'Congo-Kinshasa', hoofdstad: 'Kinshasa', werelddeel: 'Afrika', lat: -4, lon: 21.8 },
  { iso2: 'CR', naam: 'Costa Rica', hoofdstad: 'San José', werelddeel: 'Noord-Amerika', lat: 9.7, lon: -83.8 },
  { iso2: 'CU', naam: 'Cuba', hoofdstad: 'Havana', werelddeel: 'Noord-Amerika', lat: 21.5, lon: -79.5 },
  { iso2: 'CY', naam: 'Cyprus', hoofdstad: 'Nicosia', werelddeel: 'Azië', lat: 35.1, lon: 33.4 },
  { iso2: 'DK', naam: 'Denemarken', hoofdstad: 'Kopenhagen', werelddeel: 'Europa', lat: 56.3, lon: 9.5 },
  { iso2: 'DJ', naam: 'Djibouti', hoofdstad: 'Djibouti', werelddeel: 'Afrika', lat: 11.8, lon: 42.6 },
  { iso2: 'DM', naam: 'Dominica', hoofdstad: 'Roseau', werelddeel: 'Noord-Amerika', lat: 15.4, lon: -61.4 },
  { iso2: 'DO', naam: 'Dominicaanse Republiek', hoofdstad: 'Santo Domingo', werelddeel: 'Noord-Amerika', lat: 18.7, lon: -70.2 },
  { iso2: 'DE', naam: 'Duitsland', hoofdstad: 'Berlijn', werelddeel: 'Europa', lat: 51.2, lon: 10.4 },
  { iso2: 'EC', naam: 'Ecuador', hoofdstad: 'Quito', werelddeel: 'Zuid-Amerika', lat: -1.8, lon: -78.2 },
  { iso2: 'EG', naam: 'Egypte', hoofdstad: 'Caïro', werelddeel: 'Afrika', lat: 26.8, lon: 30.8 },
  { iso2: 'SV', naam: 'El Salvador', hoofdstad: 'San Salvador', werelddeel: 'Noord-Amerika', lat: 13.8, lon: -88.9 },
  { iso2: 'GQ', naam: 'Equatoriaal-Guinea', hoofdstad: 'Malabo', werelddeel: 'Afrika', lat: 1.6, lon: 10.3 },
  { iso2: 'ER', naam: 'Eritrea', hoofdstad: 'Asmara', werelddeel: 'Afrika', lat: 15.2, lon: 39.8 },
  { iso2: 'EE', naam: 'Estland', hoofdstad: 'Tallinn', werelddeel: 'Europa', lat: 58.6, lon: 25 },
  { iso2: 'SZ', naam: 'Eswatini', hoofdstad: 'Mbabane', werelddeel: 'Afrika', lat: -26.5, lon: 31.5 },
  { iso2: 'ET', naam: 'Ethiopië', hoofdstad: 'Addis Abeba', werelddeel: 'Afrika', lat: 9.1, lon: 40.5 },
  { iso2: 'FJ', naam: 'Fiji', hoofdstad: 'Suva', werelddeel: 'Oceanië', lat: -17.7, lon: 178.1 },
  { iso2: 'PH', naam: 'Filipijnen', hoofdstad: 'Manilla', werelddeel: 'Azië', lat: 12.9, lon: 121.8 },
  { iso2: 'FI', naam: 'Finland', hoofdstad: 'Helsinki', werelddeel: 'Europa', lat: 64, lon: 26 },
  { iso2: 'FR', naam: 'Frankrijk', hoofdstad: 'Parijs', werelddeel: 'Europa', lat: 46.2, lon: 2.2 },
  { iso2: 'GA', naam: 'Gabon', hoofdstad: 'Libreville', werelddeel: 'Afrika', lat: -0.8, lon: 11.6 },
  { iso2: 'GM', naam: 'Gambia', hoofdstad: 'Banjul', werelddeel: 'Afrika', lat: 13.4, lon: -15.3 },
  { iso2: 'GE', naam: 'Georgië', hoofdstad: 'Tbilisi', werelddeel: 'Azië', lat: 42.3, lon: 43.4 },
  { iso2: 'GH', naam: 'Ghana', hoofdstad: 'Accra', werelddeel: 'Afrika', lat: 7.9, lon: -1 },
  { iso2: 'GD', naam: 'Grenada', hoofdstad: 'Saint George\'s', werelddeel: 'Noord-Amerika', lat: 12.1, lon: -61.7 },
  { iso2: 'GR', naam: 'Griekenland', hoofdstad: 'Athene', werelddeel: 'Europa', lat: 39.1, lon: 21.8 },
  { iso2: 'GT', naam: 'Guatemala', hoofdstad: 'Guatem-Stad', werelddeel: 'Noord-Amerika', lat: 15.8, lon: -90.2 },
  { iso2: 'GN', naam: 'Guinee', hoofdstad: 'Conakry', werelddeel: 'Afrika', lat: 9.9, lon: -11 },
  { iso2: 'GW', naam: 'Guinee-Bissau', hoofdstad: 'Bissau', werelddeel: 'Afrika', lat: 11.8, lon: -15.2 },
  { iso2: 'GY', naam: 'Guyana', hoofdstad: 'Georgetown', werelddeel: 'Zuid-Amerika', lat: 4.9, lon: -58.9 },
  { iso2: 'HT', naam: 'Haïti', hoofdstad: 'Port-au-Prince', werelddeel: 'Noord-Amerika', lat: 19, lon: -72.3 },
  { iso2: 'HN', naam: 'Honduras', hoofdstad: 'Tegucigalpa', werelddeel: 'Noord-Amerika', lat: 15.2, lon: -86.2 },
  { iso2: 'HU', naam: 'Hongarije', hoofdstad: 'Boedapest', werelddeel: 'Europa', lat: 47.2, lon: 19.5 },
  { iso2: 'IE', naam: 'Ierland', hoofdstad: 'Dublin', werelddeel: 'Europa', lat: 53.4, lon: -8.2 },
  { iso2: 'IS', naam: 'IJsland', hoofdstad: 'Reykjavik', werelddeel: 'Europa', lat: 64.9, lon: -19 },
  { iso2: 'IN', naam: 'India', hoofdstad: 'New Delhi', werelddeel: 'Azië', lat: 20.6, lon: 79 },
  { iso2: 'ID', naam: 'Indonesië', hoofdstad: 'Jakarta', werelddeel: 'Azië', lat: -0.8, lon: 113.9 },
  { iso2: 'IQ', naam: 'Irak', hoofdstad: 'Bagdad', werelddeel: 'Azië', lat: 33.2, lon: 43.7 },
  { iso2: 'IR', naam: 'Iran', hoofdstad: 'Teheran', werelddeel: 'Azië', lat: 32.4, lon: 53.7 },
  { iso2: 'IL', naam: 'Israël', hoofdstad: 'Jeruzalem', werelddeel: 'Azië', lat: 31.5, lon: 34.9 },
  { iso2: 'IT', naam: 'Italië', hoofdstad: 'Rome', werelddeel: 'Europa', lat: 41.9, lon: 12.6 },
  { iso2: 'CI', naam: 'Ivoorkust', hoofdstad: 'Yamoussoukro', werelddeel: 'Afrika', lat: 7.5, lon: -5.5 },
  { iso2: 'JM', naam: 'Jamaica', hoofdstad: 'Kingston', werelddeel: 'Noord-Amerika', lat: 18.1, lon: -77.3 },
  { iso2: 'JP', naam: 'Japan', hoofdstad: 'Tokio', werelddeel: 'Azië', lat: 36.2, lon: 138.3 },
  { iso2: 'YE', naam: 'Jemen', hoofdstad: 'Sanaa', werelddeel: 'Azië', lat: 15.6, lon: 48 },
  { iso2: 'JO', naam: 'Jordanië', hoofdstad: 'Amman', werelddeel: 'Azië', lat: 30.6, lon: 36.2 },
  { iso2: 'CV', naam: 'Kaapverdië', hoofdstad: 'Praia', werelddeel: 'Afrika', lat: 16, lon: -24 },
  { iso2: 'CM', naam: 'Kameroen', hoofdstad: 'Yaoundé', werelddeel: 'Afrika', lat: 7.4, lon: 12.4 },
  { iso2: 'KZ', naam: 'Kazachstan', hoofdstad: 'Astana', werelddeel: 'Azië', lat: 48, lon: 66.9 },
  { iso2: 'KE', naam: 'Kenia', hoofdstad: 'Nairobi', werelddeel: 'Afrika', lat: 0, lon: 37.9 },
  { iso2: 'KG', naam: 'Kirgizië', hoofdstad: 'Bisjkek', werelddeel: 'Azië', lat: 41.2, lon: 74.8 },
  { iso2: 'KI', naam: 'Kiribati', hoofdstad: 'Tarawa', werelddeel: 'Oceanië', lat: 1.9, lon: 173 },
  { iso2: 'KW', naam: 'Koeweit', hoofdstad: 'Koeweit', werelddeel: 'Azië', lat: 29.3, lon: 47.5 },
  { iso2: 'HR', naam: 'Kroatië', hoofdstad: 'Zagreb', werelddeel: 'Europa', lat: 45.1, lon: 15.2 },
  { iso2: 'LA', naam: 'Laos', hoofdstad: 'Vientiane', werelddeel: 'Azië', lat: 19.9, lon: 102.5 },
  { iso2: 'LS', naam: 'Lesotho', hoofdstad: 'Maseru', werelddeel: 'Afrika', lat: -29.6, lon: 28.2 },
  { iso2: 'LV', naam: 'Letland', hoofdstad: 'Riga', werelddeel: 'Europa', lat: 56.9, lon: 24.6 },
  { iso2: 'LB', naam: 'Libanon', hoofdstad: 'Beiroet', werelddeel: 'Azië', lat: 33.9, lon: 35.9 },
  { iso2: 'LR', naam: 'Liberia', hoofdstad: 'Monrovia', werelddeel: 'Afrika', lat: 6.4, lon: -9.4 },
  { iso2: 'LY', naam: 'Libië', hoofdstad: 'Tripoli', werelddeel: 'Afrika', lat: 26.3, lon: 17.2 },
  { iso2: 'LI', naam: 'Liechtenstein', hoofdstad: 'Vaduz', werelddeel: 'Europa', lat: 47.2, lon: 9.6 },
  { iso2: 'LT', naam: 'Litouwen', hoofdstad: 'Vilnius', werelddeel: 'Europa', lat: 55.2, lon: 23.9 },
  { iso2: 'LU', naam: 'Luxemburg', hoofdstad: 'Luxemburg', werelddeel: 'Europa', lat: 49.8, lon: 6.1 },
  { iso2: 'MG', naam: 'Madagaskar', hoofdstad: 'Antananarivo', werelddeel: 'Afrika', lat: -18.8, lon: 46.9 },
  { iso2: 'MW', naam: 'Malawi', hoofdstad: 'Lilongwe', werelddeel: 'Afrika', lat: -13.3, lon: 34.3 },
  { iso2: 'MV', naam: 'Maldiven', hoofdstad: 'Malé', werelddeel: 'Azië', lat: 3.2, lon: 73.2 },
  { iso2: 'MY', naam: 'Maleisië', hoofdstad: 'Kuala Lumpur', werelddeel: 'Azië', lat: 4.2, lon: 101.9 },
  { iso2: 'ML', naam: 'Mali', hoofdstad: 'Bamako', werelddeel: 'Afrika', lat: 17.6, lon: -4 },
  { iso2: 'MT', naam: 'Malta', hoofdstad: 'Valletta', werelddeel: 'Europa', lat: 35.9, lon: 14.4 },
  { iso2: 'MA', naam: 'Marokko', hoofdstad: 'Rabat', werelddeel: 'Afrika', lat: 31.8, lon: -7.1 },
  { iso2: 'MH', naam: 'Marshalleilanden', hoofdstad: 'Majuro', werelddeel: 'Oceanië', lat: 7.1, lon: 171.2 },
  { iso2: 'MR', naam: 'Mauritanië', hoofdstad: 'Nouakchott', werelddeel: 'Afrika', lat: 21, lon: -10.9 },
  { iso2: 'MU', naam: 'Mauritius', hoofdstad: 'Port Louis', werelddeel: 'Afrika', lat: -20.3, lon: 57.6 },
  { iso2: 'MX', naam: 'Mexico', hoofdstad: 'Mexico-Stad', werelddeel: 'Noord-Amerika', lat: 23.6, lon: -102.6 },
  { iso2: 'FM', naam: 'Micronesia', hoofdstad: 'Palikir', werelddeel: 'Oceanië', lat: 6.9, lon: 158.2 },
  { iso2: 'MD', naam: 'Moldavië', hoofdstad: 'Chisinau', werelddeel: 'Europa', lat: 47.4, lon: 28.4 },
  { iso2: 'MC', naam: 'Monaco', hoofdstad: 'Monaco', werelddeel: 'Europa', lat: 43.7, lon: 7.4 },
  { iso2: 'MN', naam: 'Mongolië', hoofdstad: 'Ulaanbaatar', werelddeel: 'Azië', lat: 46.9, lon: 103.8 },
  { iso2: 'ME', naam: 'Montenegro', hoofdstad: 'Podgorica', werelddeel: 'Europa', lat: 42.7, lon: 19.4 },
  { iso2: 'MZ', naam: 'Mozambique', hoofdstad: 'Maputo', werelddeel: 'Afrika', lat: -18.7, lon: 35.5 },
  { iso2: 'MM', naam: 'Myanmar', hoofdstad: 'Naypyidaw', werelddeel: 'Azië', lat: 21.9, lon: 95.9 },
  { iso2: 'NA', naam: 'Namibië', hoofdstad: 'Windhoek', werelddeel: 'Afrika', lat: -22.9, lon: 18.5 },
  { iso2: 'NR', naam: 'Nauru', hoofdstad: 'Yaren', werelddeel: 'Oceanië', lat: -0.5, lon: 166.9 },
  { iso2: 'NL', naam: 'Nederland', hoofdstad: 'Amsterdam', werelddeel: 'Europa', lat: 52.1, lon: 5.3 },
  { iso2: 'NP', naam: 'Nepal', hoofdstad: 'Kathmandu', werelddeel: 'Azië', lat: 28.4, lon: 84.1 },
  { iso2: 'NI', naam: 'Nicaragua', hoofdstad: 'Managua', werelddeel: 'Noord-Amerika', lat: 12.9, lon: -85.2 },
  { iso2: 'NZ', naam: 'Nieuw-Zeeland', hoofdstad: 'Wellington', werelddeel: 'Oceanië', lat: -40.9, lon: 174.9 },
  { iso2: 'NE', naam: 'Niger', hoofdstad: 'Niamey', werelddeel: 'Afrika', lat: 17.6, lon: 8.1 },
  { iso2: 'NG', naam: 'Nigeria', hoofdstad: 'Abuja', werelddeel: 'Afrika', lat: 9.1, lon: 8.7 },
  { iso2: 'KP', naam: 'Noord-Korea', hoofdstad: 'Pyongyang', werelddeel: 'Azië', lat: 40.3, lon: 127.5 },
  { iso2: 'MK', naam: 'Noord-Macedonië', hoofdstad: 'Skopje', werelddeel: 'Europa', lat: 41.6, lon: 21.7 },
  { iso2: 'NO', naam: 'Noorwegen', hoofdstad: 'Oslo', werelddeel: 'Europa', lat: 60.5, lon: 8.5 },
  { iso2: 'UG', naam: 'Oeganda', hoofdstad: 'Kampala', werelddeel: 'Afrika', lat: 1.4, lon: 32.3 },
  { iso2: 'UA', naam: 'Oekraïne', hoofdstad: 'Kiev', werelddeel: 'Europa', lat: 48.4, lon: 31.2 },
  { iso2: 'UZ', naam: 'Oezbekistan', hoofdstad: 'Tasjkent', werelddeel: 'Azië', lat: 41.4, lon: 64.6 },
  { iso2: 'OM', naam: 'Oman', hoofdstad: 'Masqat', werelddeel: 'Azië', lat: 21.5, lon: 55.9 },
  { iso2: 'TL', naam: 'Oost-Timor', hoofdstad: 'Dili', werelddeel: 'Azië', lat: -8.9, lon: 125.7 },
  { iso2: 'AT', naam: 'Oostenrijk', hoofdstad: 'Wenen', werelddeel: 'Europa', lat: 47.5, lon: 14.6 },
  { iso2: 'PK', naam: 'Pakistan', hoofdstad: 'Islamabad', werelddeel: 'Azië', lat: 30.4, lon: 69.3 },
  { iso2: 'PW', naam: 'Palau', hoofdstad: 'Ngerulmud', werelddeel: 'Oceanië', lat: 7.5, lon: 134.6 },
  { iso2: 'PS', naam: 'Palestina', hoofdstad: 'Ramallah', werelddeel: 'Azië', lat: 31.9, lon: 35.2 },
  { iso2: 'PA', naam: 'Panama', hoofdstad: 'Panama-Stad', werelddeel: 'Noord-Amerika', lat: 8.5, lon: -80.8 },
  { iso2: 'PG', naam: 'Papoea-Nieuw-Guinea', hoofdstad: 'Port Moresby', werelddeel: 'Oceanië', lat: -6.3, lon: 143.9 },
  { iso2: 'PY', naam: 'Paraguay', hoofdstad: 'Asunción', werelddeel: 'Zuid-Amerika', lat: -23.4, lon: -58.4 },
  { iso2: 'PE', naam: 'Peru', hoofdstad: 'Lima', werelddeel: 'Zuid-Amerika', lat: -9.2, lon: -75 },
  { iso2: 'PL', naam: 'Polen', hoofdstad: 'Warschau', werelddeel: 'Europa', lat: 51.9, lon: 19.1 },
  { iso2: 'PT', naam: 'Portugal', hoofdstad: 'Lissabon', werelddeel: 'Europa', lat: 39.4, lon: -8.2 },
  { iso2: 'QA', naam: 'Qatar', hoofdstad: 'Doha', werelddeel: 'Azië', lat: 25.4, lon: 51.2 },
  { iso2: 'RO', naam: 'Roemenië', hoofdstad: 'Boekarest', werelddeel: 'Europa', lat: 45.9, lon: 25 },
  { iso2: 'RU', naam: 'Rusland', hoofdstad: 'Moskou', werelddeel: 'Europa', lat: 61.5, lon: 105.3 },
  { iso2: 'RW', naam: 'Rwanda', hoofdstad: 'Kigali', werelddeel: 'Afrika', lat: -1.9, lon: 29.9 },
  { iso2: 'KN', naam: 'Saint Kitts en Nevis', hoofdstad: 'Basseterre', werelddeel: 'Noord-Amerika', lat: 17.4, lon: -62.8 },
  { iso2: 'LC', naam: 'Saint Lucia', hoofdstad: 'Castries', werelddeel: 'Noord-Amerika', lat: 13.9, lon: -61 },
  { iso2: 'VC', naam: 'Saint Vincent en de Grenadines', hoofdstad: 'Kingstown', werelddeel: 'Noord-Amerika', lat: 13, lon: -61.2 },
  { iso2: 'SB', naam: 'Salomonseilanden', hoofdstad: 'Honiara', werelddeel: 'Oceanië', lat: -9.6, lon: 160.2 },
  { iso2: 'WS', naam: 'Samoa', hoofdstad: 'Apia', werelddeel: 'Oceanië', lat: -13.8, lon: -172.1 },
  { iso2: 'SM', naam: 'San Marino', hoofdstad: 'San Marino', werelddeel: 'Europa', lat: 43.9, lon: 12.5 },
  { iso2: 'ST', naam: 'Sao Tomé en Principe', hoofdstad: 'Sao Tomé', werelddeel: 'Afrika', lat: 0.2, lon: 6.6 },
  { iso2: 'SA', naam: 'Saoedi-Arabië', hoofdstad: 'Riyad', werelddeel: 'Azië', lat: 23.9, lon: 45.1 },
  { iso2: 'SN', naam: 'Senegal', hoofdstad: 'Dakar', werelddeel: 'Afrika', lat: 14.5, lon: -14.5 },
  { iso2: 'RS', naam: 'Servië', hoofdstad: 'Belgrado', werelddeel: 'Europa', lat: 44, lon: 21 },
  { iso2: 'SC', naam: 'Seychellen', hoofdstad: 'Victoria', werelddeel: 'Afrika', lat: -4.7, lon: 55.5 },
  { iso2: 'SL', naam: 'Sierra Leone', hoofdstad: 'Freetown', werelddeel: 'Afrika', lat: 8.5, lon: -11.8 },
  { iso2: 'SG', naam: 'Singapore', hoofdstad: 'Singapore', werelddeel: 'Azië', lat: 1.4, lon: 103.8 },
  { iso2: 'SI', naam: 'Slovenië', hoofdstad: 'Ljubljana', werelddeel: 'Europa', lat: 46.2, lon: 15 },
  { iso2: 'SK', naam: 'Slowakije', hoofdstad: 'Bratislava', werelddeel: 'Europa', lat: 48.7, lon: 19.7 },
  { iso2: 'SD', naam: 'Soedan', hoofdstad: 'Khartoem', werelddeel: 'Afrika', lat: 12.9, lon: 30.2 },
  { iso2: 'SO', naam: 'Somalië', hoofdstad: 'Mogadishu', werelddeel: 'Afrika', lat: 5.2, lon: 46.2 },
  { iso2: 'ES', naam: 'Spanje', hoofdstad: 'Madrid', werelddeel: 'Europa', lat: 40.5, lon: -3.7 },
  { iso2: 'LK', naam: 'Sri Lanka', hoofdstad: 'Sri Jayawardenepura Kotte', werelddeel: 'Azië', lat: 7.9, lon: 80.8 },
  { iso2: 'SR', naam: 'Suriname', hoofdstad: 'Paramaribo', werelddeel: 'Zuid-Amerika', lat: 4, lon: -56 },
  { iso2: 'SY', naam: 'Syrië', hoofdstad: 'Damascus', werelddeel: 'Azië', lat: 34.8, lon: 39 },
  { iso2: 'TJ', naam: 'Tadzjikistan', hoofdstad: 'Doesjanbe', werelddeel: 'Azië', lat: 38.9, lon: 71.3 },
  { iso2: 'TZ', naam: 'Tanzania', hoofdstad: 'Dodoma', werelddeel: 'Afrika', lat: -6.4, lon: 34.9 },
  { iso2: 'TH', naam: 'Thailand', hoofdstad: 'Bangkok', werelddeel: 'Azië', lat: 15.9, lon: 100.9 },
  { iso2: 'TG', naam: 'Togo', hoofdstad: 'Lomé', werelddeel: 'Afrika', lat: 8.6, lon: 0.8 },
  { iso2: 'TO', naam: 'Tonga', hoofdstad: 'Nuku\'alofa', werelddeel: 'Oceanië', lat: -21.2, lon: -175.2 },
  { iso2: 'TT', naam: 'Trinidad en Tobago', hoofdstad: 'Port of Spain', werelddeel: 'Noord-Amerika', lat: 10.7, lon: -61.2 },
  { iso2: 'TD', naam: 'Tsjaad', hoofdstad: 'N\'Djamena', werelddeel: 'Afrika', lat: 15.5, lon: 18.7 },
  { iso2: 'CZ', naam: 'Tsjechië', hoofdstad: 'Praag', werelddeel: 'Europa', lat: 49.8, lon: 15.5 },
  { iso2: 'TN', naam: 'Tunesië', hoofdstad: 'Tunis', werelddeel: 'Afrika', lat: 33.9, lon: 9.6 },
  { iso2: 'TR', naam: 'Turkije', hoofdstad: 'Ankara', werelddeel: 'Azië', lat: 38.9, lon: 35.2 },
  { iso2: 'TM', naam: 'Turkmenistan', hoofdstad: 'Asjchabad', werelddeel: 'Azië', lat: 38.9, lon: 59.6 },
  { iso2: 'TV', naam: 'Tuvalu', hoofdstad: 'Funafuti', werelddeel: 'Oceanië', lat: -7.1, lon: 177.6 },
  { iso2: 'UY', naam: 'Uruguay', hoofdstad: 'Montevideo', werelddeel: 'Zuid-Amerika', lat: -32.5, lon: -55.8 },
  { iso2: 'VU', naam: 'Vanuatu', hoofdstad: 'Port Vila', werelddeel: 'Oceanië', lat: -15.4, lon: 166.9 },
  { iso2: 'VA', naam: 'Vaticaanstad', hoofdstad: 'Vaticaanstad', werelddeel: 'Europa', lat: 41.9, lon: 12.5 },
  { iso2: 'VE', naam: 'Venezuela', hoofdstad: 'Caracas', werelddeel: 'Zuid-Amerika', lat: 6.4, lon: -66.6 },
  { iso2: 'GB', naam: 'Verenigd Koninkrijk', hoofdstad: 'Londen', werelddeel: 'Europa', lat: 54, lon: -2.5 },
  { iso2: 'AE', naam: 'Verenigde Arabische Emiraten', hoofdstad: 'Abu Dhabi', werelddeel: 'Azië', lat: 23.4, lon: 53.8 },
  { iso2: 'US', naam: 'Verenigde Staten', hoofdstad: 'Washington', werelddeel: 'Noord-Amerika', lat: 39.8, lon: -98.6 },
  { iso2: 'VN', naam: 'Vietnam', hoofdstad: 'Hanoi', werelddeel: 'Azië', lat: 14.1, lon: 108.3 },
  { iso2: 'BY', naam: 'Wit-Rusland', hoofdstad: 'Minsk', werelddeel: 'Europa', lat: 53.7, lon: 27.9 },
  { iso2: 'ZM', naam: 'Zambia', hoofdstad: 'Lusaka', werelddeel: 'Afrika', lat: -13.1, lon: 27.8 },
  { iso2: 'ZW', naam: 'Zimbabwe', hoofdstad: 'Harare', werelddeel: 'Afrika', lat: -19, lon: 29.2 },
  { iso2: 'ZA', naam: 'Zuid-Afrika', hoofdstad: 'Pretoria', werelddeel: 'Afrika', lat: -30.6, lon: 22.9 },
  { iso2: 'KR', naam: 'Zuid-Korea', hoofdstad: 'Seoel', werelddeel: 'Azië', lat: 35.9, lon: 127.8 },
  { iso2: 'SS', naam: 'Zuid-Soedan', hoofdstad: 'Juba', werelddeel: 'Afrika', lat: 7, lon: 30 },
  { iso2: 'SE', naam: 'Zweden', hoofdstad: 'Stockholm', werelddeel: 'Europa', lat: 60.1, lon: 18.6 },
  { iso2: 'CH', naam: 'Zwitserland', hoofdstad: 'Bern', werelddeel: 'Europa', lat: 46.8, lon: 8.2 },
]

// Vlag-emoji uit de ISO-landcode (regional indicator symbols).
export function vlagEmoji(iso2: string): string {
  return iso2.toUpperCase().replace(/[A-Z]/g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}
