// Munteenheid per land (ISO-alpha2), afgeleid uit het world-countries-pakket.

export type Valuta = { code: string; naam: string; symbool: string }

export const VALUTA: Record<string, Valuta> = {
  AF: { code: 'AFN', naam: 'Afghan afghani', symbool: '؋' },
  AL: { code: 'ALL', naam: 'Albanian lek', symbool: 'L' },
  DZ: { code: 'DZD', naam: 'Algerian dinar', symbool: 'د.ج' },
  AD: { code: 'EUR', naam: 'Euro', symbool: '€' },
  AO: { code: 'AOA', naam: 'Angolan kwanza', symbool: 'Kz' },
  AG: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  AR: { code: 'ARS', naam: 'Argentine peso', symbool: '$' },
  AM: { code: 'AMD', naam: 'Armenian dram', symbool: '֏' },
  AU: { code: 'AUD', naam: 'Australian dollar', symbool: '$' },
  AZ: { code: 'AZN', naam: 'Azerbaijani manat', symbool: '₼' },
  BS: { code: 'BSD', naam: 'Bahamian dollar', symbool: '$' },
  BH: { code: 'BHD', naam: 'Bahraini dinar', symbool: '.د.ب' },
  BD: { code: 'BDT', naam: 'Bangladeshi taka', symbool: '৳' },
  BB: { code: 'BBD', naam: 'Barbadian dollar', symbool: '$' },
  BE: { code: 'EUR', naam: 'Euro', symbool: '€' },
  BZ: { code: 'BZD', naam: 'Belize dollar', symbool: '$' },
  BJ: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  BT: { code: 'BTN', naam: 'Bhutanese ngultrum', symbool: 'Nu.' },
  BO: { code: 'BOB', naam: 'Bolivian boliviano', symbool: 'Bs.' },
  BA: { code: 'BAM', naam: 'Bosnia and Herzegovina convertible mark', symbool: 'KM' },
  BW: { code: 'BWP', naam: 'Botswana pula', symbool: 'P' },
  BR: { code: 'BRL', naam: 'Brazilian real', symbool: 'R$' },
  BN: { code: 'BND', naam: 'Brunei dollar', symbool: '$' },
  BG: { code: 'BGN', naam: 'Bulgarian lev', symbool: 'лв' },
  BF: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  BI: { code: 'BIF', naam: 'Burundian franc', symbool: 'Fr' },
  KH: { code: 'KHR', naam: 'Cambodian riel', symbool: '៛' },
  CA: { code: 'CAD', naam: 'Canadian dollar', symbool: '$' },
  CF: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  CL: { code: 'CLP', naam: 'Chilean peso', symbool: '$' },
  CN: { code: 'CNY', naam: 'Chinese yuan', symbool: '¥' },
  CO: { code: 'COP', naam: 'Colombian peso', symbool: '$' },
  KM: { code: 'KMF', naam: 'Comorian franc', symbool: 'Fr' },
  CG: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  CD: { code: 'CDF', naam: 'Congolese franc', symbool: 'FC' },
  CR: { code: 'CRC', naam: 'Costa Rican colón', symbool: '₡' },
  CU: { code: 'CUC', naam: 'Cuban convertible peso', symbool: '$' },
  CY: { code: 'EUR', naam: 'Euro', symbool: '€' },
  DK: { code: 'DKK', naam: 'Danish krone', symbool: 'kr' },
  DJ: { code: 'DJF', naam: 'Djiboutian franc', symbool: 'Fr' },
  DM: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  DO: { code: 'DOP', naam: 'Dominican peso', symbool: '$' },
  DE: { code: 'EUR', naam: 'Euro', symbool: '€' },
  EC: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  EG: { code: 'EGP', naam: 'Egyptian pound', symbool: '£' },
  SV: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  GQ: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  ER: { code: 'ERN', naam: 'Eritrean nakfa', symbool: 'Nfk' },
  EE: { code: 'EUR', naam: 'Euro', symbool: '€' },
  SZ: { code: 'SZL', naam: 'Swazi lilangeni', symbool: 'L' },
  ET: { code: 'ETB', naam: 'Ethiopian birr', symbool: 'Br' },
  FJ: { code: 'FJD', naam: 'Fijian dollar', symbool: '$' },
  PH: { code: 'PHP', naam: 'Philippine peso', symbool: '₱' },
  FI: { code: 'EUR', naam: 'Euro', symbool: '€' },
  FR: { code: 'EUR', naam: 'Euro', symbool: '€' },
  GA: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  GM: { code: 'GMD', naam: 'dalasi', symbool: 'D' },
  GE: { code: 'GEL', naam: 'lari', symbool: '₾' },
  GH: { code: 'GHS', naam: 'Ghanaian cedi', symbool: '₵' },
  GD: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  GR: { code: 'EUR', naam: 'Euro', symbool: '€' },
  GT: { code: 'GTQ', naam: 'Guatemalan quetzal', symbool: 'Q' },
  GN: { code: 'GNF', naam: 'Guinean franc', symbool: 'Fr' },
  GW: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  GY: { code: 'GYD', naam: 'Guyanese dollar', symbool: '$' },
  HT: { code: 'HTG', naam: 'Haitian gourde', symbool: 'G' },
  HN: { code: 'HNL', naam: 'Honduran lempira', symbool: 'L' },
  HU: { code: 'HUF', naam: 'Hungarian forint', symbool: 'Ft' },
  IE: { code: 'EUR', naam: 'Euro', symbool: '€' },
  IS: { code: 'ISK', naam: 'Icelandic króna', symbool: 'kr' },
  IN: { code: 'INR', naam: 'Indian rupee', symbool: '₹' },
  ID: { code: 'IDR', naam: 'Indonesian rupiah', symbool: 'Rp' },
  IQ: { code: 'IQD', naam: 'Iraqi dinar', symbool: 'ع.د' },
  IR: { code: 'IRR', naam: 'Iranian rial', symbool: '﷼' },
  IL: { code: 'ILS', naam: 'Israeli new shekel', symbool: '₪' },
  IT: { code: 'EUR', naam: 'Euro', symbool: '€' },
  CI: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  JM: { code: 'JMD', naam: 'Jamaican dollar', symbool: '$' },
  JP: { code: 'JPY', naam: 'Japanese yen', symbool: '¥' },
  YE: { code: 'YER', naam: 'Yemeni rial', symbool: '﷼' },
  JO: { code: 'JOD', naam: 'Jordanian dinar', symbool: 'د.ا' },
  CV: { code: 'CVE', naam: 'Cape Verdean escudo', symbool: 'Esc' },
  CM: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  KZ: { code: 'KZT', naam: 'Kazakhstani tenge', symbool: '₸' },
  KE: { code: 'KES', naam: 'Kenyan shilling', symbool: 'Sh' },
  KG: { code: 'KGS', naam: 'Kyrgyzstani som', symbool: 'с' },
  KI: { code: 'AUD', naam: 'Australian dollar', symbool: '$' },
  KW: { code: 'KWD', naam: 'Kuwaiti dinar', symbool: 'د.ك' },
  HR: { code: 'EUR', naam: 'Euro', symbool: '€' },
  LA: { code: 'LAK', naam: 'Lao kip', symbool: '₭' },
  LS: { code: 'LSL', naam: 'Lesotho loti', symbool: 'L' },
  LV: { code: 'EUR', naam: 'Euro', symbool: '€' },
  LB: { code: 'LBP', naam: 'Lebanese pound', symbool: 'ل.ل' },
  LR: { code: 'LRD', naam: 'Liberian dollar', symbool: '$' },
  LY: { code: 'LYD', naam: 'Libyan dinar', symbool: 'ل.د' },
  LI: { code: 'CHF', naam: 'Swiss franc', symbool: 'Fr' },
  LT: { code: 'EUR', naam: 'Euro', symbool: '€' },
  LU: { code: 'EUR', naam: 'Euro', symbool: '€' },
  MG: { code: 'MGA', naam: 'Malagasy ariary', symbool: 'Ar' },
  MW: { code: 'MWK', naam: 'Malawian kwacha', symbool: 'MK' },
  MV: { code: 'MVR', naam: 'Maldivian rufiyaa', symbool: '.ރ' },
  MY: { code: 'MYR', naam: 'Malaysian ringgit', symbool: 'RM' },
  ML: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  MT: { code: 'EUR', naam: 'Euro', symbool: '€' },
  MA: { code: 'MAD', naam: 'Moroccan dirham', symbool: 'د.م.' },
  MH: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  MR: { code: 'MRU', naam: 'Mauritanian ouguiya', symbool: 'UM' },
  MU: { code: 'MUR', naam: 'Mauritian rupee', symbool: '₨' },
  MX: { code: 'MXN', naam: 'Mexican peso', symbool: '$' },
  FM: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  MD: { code: 'MDL', naam: 'Moldovan leu', symbool: 'L' },
  MC: { code: 'EUR', naam: 'Euro', symbool: '€' },
  MN: { code: 'MNT', naam: 'Mongolian tögrög', symbool: '₮' },
  ME: { code: 'EUR', naam: 'Euro', symbool: '€' },
  MZ: { code: 'MZN', naam: 'Mozambican metical', symbool: 'MT' },
  MM: { code: 'MMK', naam: 'Burmese kyat', symbool: 'Ks' },
  NA: { code: 'NAD', naam: 'Namibian dollar', symbool: '$' },
  NR: { code: 'AUD', naam: 'Australian dollar', symbool: '$' },
  NL: { code: 'EUR', naam: 'Euro', symbool: '€' },
  NP: { code: 'NPR', naam: 'Nepalese rupee', symbool: '₨' },
  NI: { code: 'NIO', naam: 'Nicaraguan córdoba', symbool: 'C$' },
  NZ: { code: 'NZD', naam: 'New Zealand dollar', symbool: '$' },
  NE: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  NG: { code: 'NGN', naam: 'Nigerian naira', symbool: '₦' },
  KP: { code: 'KPW', naam: 'North Korean won', symbool: '₩' },
  MK: { code: 'MKD', naam: 'denar', symbool: 'den' },
  NO: { code: 'NOK', naam: 'Norwegian krone', symbool: 'kr' },
  UG: { code: 'UGX', naam: 'Ugandan shilling', symbool: 'Sh' },
  UA: { code: 'UAH', naam: 'Ukrainian hryvnia', symbool: '₴' },
  UZ: { code: 'UZS', naam: 'Uzbekistani soʻm', symbool: 'so\'m' },
  OM: { code: 'OMR', naam: 'Omani rial', symbool: 'ر.ع.' },
  TL: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  AT: { code: 'EUR', naam: 'Euro', symbool: '€' },
  PK: { code: 'PKR', naam: 'Pakistani rupee', symbool: '₨' },
  PW: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  PS: { code: 'EGP', naam: 'Egyptian pound', symbool: 'E£' },
  PA: { code: 'PAB', naam: 'Panamanian balboa', symbool: 'B/.' },
  PG: { code: 'PGK', naam: 'Papua New Guinean kina', symbool: 'K' },
  PY: { code: 'PYG', naam: 'Paraguayan guaraní', symbool: '₲' },
  PE: { code: 'PEN', naam: 'Peruvian sol', symbool: 'S/.' },
  PL: { code: 'PLN', naam: 'Polish złoty', symbool: 'zł' },
  PT: { code: 'EUR', naam: 'Euro', symbool: '€' },
  QA: { code: 'QAR', naam: 'Qatari riyal', symbool: 'ر.ق' },
  RO: { code: 'RON', naam: 'Romanian leu', symbool: 'lei' },
  RU: { code: 'RUB', naam: 'Russian ruble', symbool: '₽' },
  RW: { code: 'RWF', naam: 'Rwandan franc', symbool: 'Fr' },
  KN: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  LC: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  VC: { code: 'XCD', naam: 'Eastern Caribbean dollar', symbool: '$' },
  SB: { code: 'SBD', naam: 'Solomon Islands dollar', symbool: '$' },
  WS: { code: 'WST', naam: 'Samoan tālā', symbool: 'T' },
  SM: { code: 'EUR', naam: 'Euro', symbool: '€' },
  ST: { code: 'STN', naam: 'São Tomé and Príncipe dobra', symbool: 'Db' },
  SA: { code: 'SAR', naam: 'Saudi riyal', symbool: 'ر.س' },
  SN: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  RS: { code: 'RSD', naam: 'Serbian dinar', symbool: 'дин.' },
  SC: { code: 'SCR', naam: 'Seychellois rupee', symbool: '₨' },
  SL: { code: 'SLL', naam: 'Sierra Leonean leone', symbool: 'Le' },
  SG: { code: 'SGD', naam: 'Singapore dollar', symbool: '$' },
  SI: { code: 'EUR', naam: 'Euro', symbool: '€' },
  SK: { code: 'EUR', naam: 'Euro', symbool: '€' },
  SD: { code: 'SDG', naam: 'Sudanese pound', symbool: 'PT' },
  SO: { code: 'SOS', naam: 'Somali shilling', symbool: 'Sh' },
  ES: { code: 'EUR', naam: 'Euro', symbool: '€' },
  LK: { code: 'LKR', naam: 'Sri Lankan rupee', symbool: 'Rs  රු' },
  SR: { code: 'SRD', naam: 'Surinamese dollar', symbool: '$' },
  SY: { code: 'SYP', naam: 'Syrian pound', symbool: '£' },
  TJ: { code: 'TJS', naam: 'Tajikistani somoni', symbool: 'ЅМ' },
  TZ: { code: 'TZS', naam: 'Tanzanian shilling', symbool: 'Sh' },
  TH: { code: 'THB', naam: 'Thai baht', symbool: '฿' },
  TG: { code: 'XOF', naam: 'West African CFA franc', symbool: 'Fr' },
  TO: { code: 'TOP', naam: 'Tongan paʻanga', symbool: 'T$' },
  TT: { code: 'TTD', naam: 'Trinidad and Tobago dollar', symbool: '$' },
  TD: { code: 'XAF', naam: 'Central African CFA franc', symbool: 'Fr' },
  CZ: { code: 'CZK', naam: 'Czech koruna', symbool: 'Kč' },
  TN: { code: 'TND', naam: 'Tunisian dinar', symbool: 'د.ت' },
  TR: { code: 'TRY', naam: 'Turkish lira', symbool: '₺' },
  TM: { code: 'TMT', naam: 'Turkmenistan manat', symbool: 'm' },
  TV: { code: 'AUD', naam: 'Australian dollar', symbool: '$' },
  UY: { code: 'UYU', naam: 'Uruguayan peso', symbool: '$' },
  VU: { code: 'VUV', naam: 'Vanuatu vatu', symbool: 'Vt' },
  VA: { code: 'EUR', naam: 'Euro', symbool: '€' },
  VE: { code: 'VES', naam: 'Venezuelan bolívar soberano', symbool: 'Bs.S.' },
  GB: { code: 'GBP', naam: 'British pound', symbool: '£' },
  AE: { code: 'AED', naam: 'United Arab Emirates dirham', symbool: 'د.إ' },
  US: { code: 'USD', naam: 'United States dollar', symbool: '$' },
  VN: { code: 'VND', naam: 'Vietnamese đồng', symbool: '₫' },
  BY: { code: 'BYN', naam: 'Belarusian ruble', symbool: 'Br' },
  ZM: { code: 'ZMW', naam: 'Zambian kwacha', symbool: 'ZK' },
  ZW: { code: 'BWP', naam: 'Botswana pula', symbool: 'P' },
  ZA: { code: 'ZAR', naam: 'South African rand', symbool: 'R' },
  KR: { code: 'KRW', naam: 'South Korean won', symbool: '₩' },
  SS: { code: 'SSP', naam: 'South Sudanese pound', symbool: '£' },
  SE: { code: 'SEK', naam: 'Swedish krona', symbool: 'kr' },
  CH: { code: 'CHF', naam: 'Swiss franc', symbool: 'Fr.' },
}
