// Spaanse basiswoordenschat, thematisch geordend. `alt` = ook goed gerekend.
export type Woord = {
  nl: string
  es: string
  alt?: string[]
}

export type Thema = {
  id: string
  titel: string
  woorden: Woord[]
}

export const THEMAS: Thema[] = [
  {
    id: 'begroeten',
    titel: 'Begroeten & beleefdheid',
    woorden: [
      { nl: 'hallo', es: 'hola' },
      { nl: 'goedemorgen', es: 'buenos días' },
      { nl: 'goedemiddag', es: 'buenas tardes' },
      { nl: 'goedenavond / goedenacht', es: 'buenas noches' },
      { nl: 'tot ziens', es: 'adiós', alt: ['hasta luego'] },
      { nl: 'tot morgen', es: 'hasta mañana' },
      { nl: 'alsjeblieft (verzoek)', es: 'por favor' },
      { nl: 'dank je wel', es: 'gracias' },
      { nl: 'graag gedaan', es: 'de nada' },
      { nl: 'sorry / pardon', es: 'perdón', alt: ['lo siento'] },
      { nl: 'ja', es: 'sí' },
      { nl: 'nee', es: 'no' },
      { nl: 'Hoe gaat het?', es: '¿Cómo estás?', alt: ['como estas', 'que tal', '¿Qué tal?'] },
      { nl: 'Goed, bedankt', es: 'Bien, gracias' },
      { nl: 'Hoe heet je?', es: '¿Cómo te llamas?', alt: ['como te llamas'] },
      { nl: 'Ik heet…', es: 'Me llamo…', alt: ['me llamo'] },
      { nl: 'Aangenaam (kennis te maken)', es: 'Mucho gusto', alt: ['encantado', 'encantada'] },
      { nl: 'welkom', es: 'bienvenido', alt: ['bienvenida'] },
      { nl: 'meneer', es: 'señor' },
      { nl: 'mevrouw', es: 'señora' },
    ],
  },
  {
    id: 'getallen',
    titel: 'Getallen',
    woorden: [
      { nl: 'een (1)', es: 'uno' },
      { nl: 'twee (2)', es: 'dos' },
      { nl: 'drie (3)', es: 'tres' },
      { nl: 'vier (4)', es: 'cuatro' },
      { nl: 'vijf (5)', es: 'cinco' },
      { nl: 'zes (6)', es: 'seis' },
      { nl: 'zeven (7)', es: 'siete' },
      { nl: 'acht (8)', es: 'ocho' },
      { nl: 'negen (9)', es: 'nueve' },
      { nl: 'tien (10)', es: 'diez' },
      { nl: 'elf (11)', es: 'once' },
      { nl: 'twaalf (12)', es: 'doce' },
      { nl: 'vijftien (15)', es: 'quince' },
      { nl: 'twintig (20)', es: 'veinte' },
      { nl: 'dertig (30)', es: 'treinta' },
      { nl: 'veertig (40)', es: 'cuarenta' },
      { nl: 'vijftig (50)', es: 'cincuenta' },
      { nl: 'honderd (100)', es: 'cien' },
      { nl: 'duizend (1000)', es: 'mil' },
      { nl: 'eerste', es: 'primero', alt: ['primera'] },
    ],
  },
  {
    id: 'familie',
    titel: 'Familie & mensen',
    woorden: [
      { nl: 'de familie', es: 'la familia' },
      { nl: 'de vader', es: 'el padre' },
      { nl: 'de moeder', es: 'la madre' },
      { nl: 'de ouders', es: 'los padres' },
      { nl: 'de broer', es: 'el hermano' },
      { nl: 'de zus', es: 'la hermana' },
      { nl: 'de zoon', es: 'el hijo' },
      { nl: 'de dochter', es: 'la hija' },
      { nl: 'de opa', es: 'el abuelo' },
      { nl: 'de oma', es: 'la abuela' },
      { nl: 'de oom', es: 'el tío' },
      { nl: 'de tante', es: 'la tía' },
      { nl: 'de man / echtgenoot', es: 'el marido', alt: ['el esposo'] },
      { nl: 'de vrouw / echtgenote', es: 'la mujer', alt: ['la esposa'] },
      { nl: 'het kind', es: 'el niño', alt: ['la niña'] },
      { nl: 'de vriend', es: 'el amigo' },
      { nl: 'de vriendin', es: 'la amiga' },
      { nl: 'de mensen', es: 'la gente' },
      { nl: 'de jongen', es: 'el chico' },
      { nl: 'het meisje', es: 'la chica' },
    ],
  },
  {
    id: 'eten',
    titel: 'Eten & drinken',
    woorden: [
      { nl: 'het water', es: 'el agua' },
      { nl: 'het brood', es: 'el pan' },
      { nl: 'de melk', es: 'la leche' },
      { nl: 'de koffie', es: 'el café' },
      { nl: 'de thee', es: 'el té' },
      { nl: 'het bier', es: 'la cerveza' },
      { nl: 'de wijn', es: 'el vino' },
      { nl: 'de kaas', es: 'el queso' },
      { nl: 'het vlees', es: 'la carne' },
      { nl: 'de vis', es: 'el pescado' },
      { nl: 'de kip', es: 'el pollo' },
      { nl: 'het ei', es: 'el huevo' },
      { nl: 'de rijst', es: 'el arroz' },
      { nl: 'de appel', es: 'la manzana' },
      { nl: 'de sinaasappel', es: 'la naranja' },
      { nl: 'de groente', es: 'la verdura' },
      { nl: 'het fruit', es: 'la fruta' },
      { nl: 'het ontbijt', es: 'el desayuno' },
      { nl: 'de lunch', es: 'el almuerzo', alt: ['la comida'] },
      { nl: 'het avondeten', es: 'la cena' },
      { nl: 'De rekening, alstublieft', es: 'La cuenta, por favor' },
      { nl: 'lekker', es: 'rico', alt: ['delicioso', 'sabroso'] },
    ],
  },
  {
    id: 'reizen',
    titel: 'Reizen & vervoer',
    woorden: [
      { nl: 'de reis', es: 'el viaje' },
      { nl: 'het vliegtuig', es: 'el avión' },
      { nl: 'de trein', es: 'el tren' },
      { nl: 'de bus', es: 'el autobús' },
      { nl: 'de auto', es: 'el coche' },
      { nl: 'de fiets', es: 'la bicicleta' },
      { nl: 'het station', es: 'la estación' },
      { nl: 'het vliegveld', es: 'el aeropuerto' },
      { nl: 'het hotel', es: 'el hotel' },
      { nl: 'het strand', es: 'la playa' },
      { nl: 'de zee', es: 'el mar' },
      { nl: 'de stad', es: 'la ciudad' },
      { nl: 'het dorp', es: 'el pueblo' },
      { nl: 'de straat', es: 'la calle' },
      { nl: 'het plein', es: 'la plaza' },
      { nl: 'het kaartje / ticket', es: 'el billete', alt: ['el boleto'] },
      { nl: 'de koffer', es: 'la maleta' },
      { nl: 'het paspoort', es: 'el pasaporte' },
      { nl: 'links', es: 'a la izquierda', alt: ['izquierda'] },
      { nl: 'rechts', es: 'a la derecha', alt: ['derecha'] },
      { nl: 'rechtdoor', es: 'todo recto', alt: ['recto'] },
      { nl: 'Waar is…?', es: '¿Dónde está…?', alt: ['donde esta'] },
    ],
  },
  {
    id: 'werkwoorden',
    titel: 'Werkwoorden (basis)',
    woorden: [
      { nl: 'zijn (eigenschap)', es: 'ser' },
      { nl: 'zijn (toestand/plaats)', es: 'estar' },
      { nl: 'hebben', es: 'tener' },
      { nl: 'gaan', es: 'ir' },
      { nl: 'komen', es: 'venir' },
      { nl: 'doen / maken', es: 'hacer' },
      { nl: 'kunnen', es: 'poder' },
      { nl: 'willen', es: 'querer' },
      { nl: 'moeten', es: 'deber', alt: ['tener que'] },
      { nl: 'spreken / praten', es: 'hablar' },
      { nl: 'eten', es: 'comer' },
      { nl: 'drinken', es: 'beber' },
      { nl: 'wonen / leven', es: 'vivir' },
      { nl: 'werken', es: 'trabajar' },
      { nl: 'kopen', es: 'comprar' },
      { nl: 'zien', es: 'ver' },
      { nl: 'weten', es: 'saber' },
      { nl: 'kennen', es: 'conocer' },
      { nl: 'geven', es: 'dar' },
      { nl: 'zeggen', es: 'decir' },
      { nl: 'slapen', es: 'dormir' },
      { nl: 'begrijpen', es: 'entender', alt: ['comprender'] },
    ],
  },
  {
    id: 'tijd',
    titel: 'Tijd & dagen',
    woorden: [
      { nl: 'vandaag', es: 'hoy' },
      { nl: 'morgen', es: 'mañana' },
      { nl: 'gisteren', es: 'ayer' },
      { nl: 'nu', es: 'ahora' },
      { nl: 'later', es: 'más tarde', alt: ['luego'] },
      { nl: 'de dag', es: 'el día' },
      { nl: 'de week', es: 'la semana' },
      { nl: 'de maand', es: 'el mes' },
      { nl: 'het jaar', es: 'el año' },
      { nl: 'het uur / de tijd', es: 'la hora' },
      { nl: 'maandag', es: 'lunes' },
      { nl: 'dinsdag', es: 'martes' },
      { nl: 'woensdag', es: 'miércoles' },
      { nl: 'donderdag', es: 'jueves' },
      { nl: 'vrijdag', es: 'viernes' },
      { nl: 'zaterdag', es: 'sábado' },
      { nl: 'zondag', es: 'domingo' },
      { nl: 'het weekend', es: 'el fin de semana' },
      { nl: 'Hoe laat is het?', es: '¿Qué hora es?', alt: ['que hora es'] },
      { nl: 'de zomer', es: 'el verano' },
      { nl: 'de winter', es: 'el invierno' },
      { nl: 'de lente', es: 'la primavera' },
      { nl: 'de herfst', es: 'el otoño' },
    ],
  },
  {
    id: 'kleuren',
    titel: 'Kleuren',
    woorden: [
      { nl: 'rood', es: 'rojo' },
      { nl: 'blauw', es: 'azul' },
      { nl: 'groen', es: 'verde' },
      { nl: 'geel', es: 'amarillo' },
      { nl: 'oranje', es: 'naranja' },
      { nl: 'zwart', es: 'negro' },
      { nl: 'wit', es: 'blanco' },
      { nl: 'grijs', es: 'gris' },
      { nl: 'bruin', es: 'marrón' },
      { nl: 'roze', es: 'rosa' },
      { nl: 'paars', es: 'morado', alt: ['violeta'] },
      { nl: 'licht (kleur)', es: 'claro' },
      { nl: 'donker (kleur)', es: 'oscuro' },
    ],
  },
  {
    id: 'lichaam',
    titel: 'Lichaam & gezondheid',
    woorden: [
      { nl: 'het hoofd', es: 'la cabeza' },
      { nl: 'het gezicht', es: 'la cara' },
      { nl: 'het oog', es: 'el ojo' },
      { nl: 'het oor', es: 'la oreja' },
      { nl: 'de neus', es: 'la nariz' },
      { nl: 'de mond', es: 'la boca' },
      { nl: 'de hand', es: 'la mano' },
      { nl: 'de arm', es: 'el brazo' },
      { nl: 'het been', es: 'la pierna' },
      { nl: 'de voet', es: 'el pie' },
      { nl: 'de rug', es: 'la espalda' },
      { nl: 'de buik', es: 'el estómago', alt: ['la barriga'] },
      { nl: 'het hart', es: 'el corazón' },
      { nl: 'ziek', es: 'enfermo', alt: ['enferma'] },
      { nl: 'gezond', es: 'sano', alt: ['sana'] },
      { nl: 'de dokter', es: 'el médico', alt: ['el doctor'] },
      { nl: 'de apotheek', es: 'la farmacia' },
      { nl: 'de pijn', es: 'el dolor' },
      { nl: 'moe', es: 'cansado', alt: ['cansada'] },
    ],
  },
  {
    id: 'huis',
    titel: 'Huis & wonen',
    woorden: [
      { nl: 'het huis', es: 'la casa' },
      { nl: 'de woning / flat', es: 'el piso', alt: ['el apartamento'] },
      { nl: 'de kamer', es: 'la habitación', alt: ['el cuarto'] },
      { nl: 'de keuken', es: 'la cocina' },
      { nl: 'de badkamer', es: 'el baño' },
      { nl: 'de slaapkamer', es: 'el dormitorio' },
      { nl: 'de woonkamer', es: 'el salón', alt: ['la sala'] },
      { nl: 'de deur', es: 'la puerta' },
      { nl: 'het raam', es: 'la ventana' },
      { nl: 'de tafel', es: 'la mesa' },
      { nl: 'de stoel', es: 'la silla' },
      { nl: 'het bed', es: 'la cama' },
      { nl: 'de trap', es: 'la escalera' },
      { nl: 'de tuin', es: 'el jardín' },
      { nl: 'de sleutel', es: 'la llave' },
      { nl: 'het licht', es: 'la luz' },
    ],
  },
  {
    id: 'kleding',
    titel: 'Kleding & winkelen',
    woorden: [
      { nl: 'de kleding', es: 'la ropa' },
      { nl: 'het T-shirt', es: 'la camiseta' },
      { nl: 'het overhemd', es: 'la camisa' },
      { nl: 'de broek', es: 'los pantalones', alt: ['el pantalón'] },
      { nl: 'de jurk', es: 'el vestido' },
      { nl: 'de rok', es: 'la falda' },
      { nl: 'de jas', es: 'el abrigo', alt: ['la chaqueta'] },
      { nl: 'de schoenen', es: 'los zapatos' },
      { nl: 'de winkel', es: 'la tienda' },
      { nl: 'de markt', es: 'el mercado' },
      { nl: 'het geld', es: 'el dinero' },
      { nl: 'de prijs', es: 'el precio' },
      { nl: 'duur', es: 'caro', alt: ['cara'] },
      { nl: 'goedkoop', es: 'barato', alt: ['barata'] },
      { nl: 'Hoeveel kost het?', es: '¿Cuánto cuesta?', alt: ['cuanto cuesta', 'cuanto es'] },
      { nl: 'groot', es: 'grande' },
      { nl: 'klein', es: 'pequeño', alt: ['pequeña'] },
      { nl: 'nieuw', es: 'nuevo', alt: ['nueva'] },
      { nl: 'oud', es: 'viejo', alt: ['vieja'] },
    ],
  },
  {
    id: 'weer',
    titel: 'Weer & natuur',
    woorden: [
      { nl: 'het weer', es: 'el tiempo' },
      { nl: 'de zon', es: 'el sol' },
      { nl: 'de regen', es: 'la lluvia' },
      { nl: 'de wind', es: 'el viento' },
      { nl: 'de sneeuw', es: 'la nieve' },
      { nl: 'de wolk', es: 'la nube' },
      { nl: 'warm / heet', es: 'caliente', alt: ['caluroso'] },
      { nl: 'koud', es: 'frío', alt: ['fria'] },
      { nl: 'Het is zonnig', es: 'Hace sol' },
      { nl: 'Het regent', es: 'Llueve', alt: ['esta lloviendo'] },
      { nl: 'Het is warm (weer)', es: 'Hace calor' },
      { nl: 'Het is koud (weer)', es: 'Hace frío' },
      { nl: 'de berg', es: 'la montaña' },
      { nl: 'de rivier', es: 'el río' },
      { nl: 'het bos', es: 'el bosque' },
      { nl: 'de bloem', es: 'la flor' },
      { nl: 'de boom', es: 'el árbol' },
      { nl: 'de hond', es: 'el perro' },
      { nl: 'de kat', es: 'el gato' },
      { nl: 'de vogel', es: 'el pájaro' },
    ],
  },
  {
    id: 'vragen',
    titel: 'Vraagwoorden & kernwoordjes',
    woorden: [
      { nl: 'wat', es: 'qué', alt: ['que'] },
      { nl: 'wie', es: 'quién', alt: ['quien'] },
      { nl: 'waar', es: 'dónde', alt: ['donde'] },
      { nl: 'wanneer', es: 'cuándo', alt: ['cuando'] },
      { nl: 'waarom', es: 'por qué', alt: ['por que'] },
      { nl: 'hoe', es: 'cómo', alt: ['como'] },
      { nl: 'hoeveel', es: 'cuánto', alt: ['cuanto'] },
      { nl: 'welke', es: 'cuál', alt: ['cual'] },
      { nl: 'en', es: 'y' },
      { nl: 'of', es: 'o' },
      { nl: 'maar', es: 'pero' },
      { nl: 'omdat', es: 'porque' },
      { nl: 'met', es: 'con' },
      { nl: 'zonder', es: 'sin' },
      { nl: 'voor', es: 'para', alt: ['por'] },
      { nl: 'in', es: 'en' },
      { nl: 'veel', es: 'mucho', alt: ['mucha'] },
      { nl: 'weinig', es: 'poco', alt: ['poca'] },
      { nl: 'alles', es: 'todo' },
      { nl: 'niets', es: 'nada' },
      { nl: 'iets', es: 'algo' },
      { nl: 'altijd', es: 'siempre' },
      { nl: 'nooit', es: 'nunca' },
    ],
  },
  {
    id: 'uitdrukkingen',
    titel: 'Handige zinnen',
    woorden: [
      { nl: 'Ik begrijp het niet', es: 'No entiendo', alt: ['no lo entiendo'] },
      { nl: 'Spreek je Engels?', es: '¿Hablas inglés?', alt: ['hablas ingles'] },
      { nl: 'Ik spreek een beetje Spaans', es: 'Hablo un poco de español' },
      { nl: 'Kun je dat herhalen?', es: '¿Puedes repetir?', alt: ['puedes repetirlo'] },
      { nl: 'Langzamer, alsjeblieft', es: 'Más despacio, por favor', alt: ['mas despacio'] },
      { nl: 'Ik weet het niet', es: 'No sé', alt: ['no lo se'] },
      { nl: 'Geen probleem', es: 'No hay problema', alt: ['no pasa nada'] },
      { nl: 'Natuurlijk', es: 'Claro', alt: ['por supuesto'] },
      { nl: 'Ik heb honger', es: 'Tengo hambre' },
      { nl: 'Ik heb dorst', es: 'Tengo sed' },
      { nl: 'Ik ben verdwaald', es: 'Estoy perdido', alt: ['estoy perdida'] },
      { nl: 'Help!', es: '¡Socorro!', alt: ['socorro', 'ayuda'] },
      { nl: 'Ik vind het leuk / lekker', es: 'Me gusta' },
      { nl: 'Ik vind het niet leuk', es: 'No me gusta' },
      { nl: 'Wat betekent dit?', es: '¿Qué significa esto?', alt: ['que significa'] },
      { nl: 'Mag ik…?', es: '¿Puedo…?', alt: ['puedo'] },
      { nl: 'Er is / er zijn', es: 'hay' },
      { nl: 'Proost!', es: '¡Salud!', alt: ['salud'] },
      { nl: 'Veel succes!', es: '¡Buena suerte!', alt: ['buena suerte'] },
      { nl: 'gefeliciteerd', es: 'felicidades', alt: ['enhorabuena'] },
    ],
  },
  {
    id: 'werk-school',
    titel: 'Werk & school',
    woorden: [
      { nl: 'het werk', es: 'el trabajo' },
      { nl: 'de school', es: 'la escuela', alt: ['el colegio'] },
      { nl: 'de leraar', es: 'el profesor', alt: ['el maestro'] },
      { nl: 'de student', es: 'el estudiante' },
      { nl: 'de les', es: 'la clase', alt: ['la lección'] },
      { nl: 'het boek', es: 'el libro' },
      { nl: 'de pen', es: 'el bolígrafo', alt: ['el boli'] },
      { nl: 'het papier', es: 'el papel' },
      { nl: 'de computer', es: 'el ordenador', alt: ['la computadora'] },
      { nl: 'de telefoon', es: 'el teléfono' },
      { nl: 'het kantoor', es: 'la oficina' },
      { nl: 'de vergadering', es: 'la reunión' },
      { nl: 'de vraag', es: 'la pregunta' },
      { nl: 'het antwoord', es: 'la respuesta' },
      { nl: 'leren / studeren', es: 'estudiar' },
      { nl: 'lezen', es: 'leer' },
      { nl: 'schrijven', es: 'escribir' },
      { nl: 'luisteren', es: 'escuchar' },
    ],
  },
]

export const ALLE_WOORDEN: (Woord & { thema: string })[] = THEMAS.flatMap((t) =>
  t.woorden.map((w) => ({ ...w, thema: t.id })),
)
