// Volledige Spaanse zinnen met Nederlandse vertaling, thematisch gegroepeerd.

export type Zin = {
  es: string
  nl: string
  thema: string
}

export const ZINNEN: Zin[] = [
  { es: '¡Hola! ¿Qué tal estás?', nl: 'Hallo! Hoe gaat het met je?', thema: 'begroeten & kennismaken' },
  { es: 'Buenos días, encantado de conocerte.', nl: 'Goedemorgen, leuk je te ontmoeten.', thema: 'begroeten & kennismaken' },
  { es: 'Me llamo Pedro, ¿y tú cómo te llamas?', nl: 'Ik heet Pedro, en hoe heet jij?', thema: 'begroeten & kennismaken' },
  { es: '¿De dónde eres?', nl: 'Waar kom je vandaan?', thema: 'begroeten & kennismaken' },
  { es: 'Soy de los Países Bajos.', nl: 'Ik kom uit Nederland.', thema: 'begroeten & kennismaken' },
  { es: '¿A qué te dedicas?', nl: 'Wat voor werk doe je?', thema: 'begroeten & kennismaken' },
  { es: 'Encantado de conocerte, que tengas un buen día.', nl: 'Aangenaam kennis te maken, nog een fijne dag.', thema: 'begroeten & kennismaken' },
  { es: '¿Hablas inglés o solo español?', nl: 'Spreek je Engels of alleen Spaans?', thema: 'begroeten & kennismaken' },
  { es: 'Perdona, no entiendo muy bien el español.', nl: 'Sorry, ik versta niet zo goed Spaans.', thema: 'begroeten & kennismaken' },
  { es: 'Hasta luego, nos vemos mañana.', nl: 'Tot ziens, we zien elkaar morgen.', thema: 'begroeten & kennismaken' },
  { es: '¿Dónde está la estación de tren?', nl: 'Waar is het treinstation?', thema: 'de weg vragen' },
  { es: '¿Cómo llego al centro de la ciudad?', nl: 'Hoe kom ik in het centrum van de stad?', thema: 'de weg vragen' },
  { es: '¿Está lejos de aquí?', nl: 'Is het ver hiervandaan?', thema: 'de weg vragen' },
  { es: 'Siga todo recto y gire a la derecha.', nl: 'Ga rechtdoor en sla rechtsaf.', thema: 'de weg vragen' },
  { es: '¿Puede indicarme el camino, por favor?', nl: 'Kunt u mij de weg wijzen, alstublieft?', thema: 'de weg vragen' },
  { es: 'Perdone, ¿hay un cajero cerca?', nl: 'Pardon, is er een pinautomaat in de buurt?', thema: 'de weg vragen' },
  { es: '¿Este autobús va al aeropuerto?', nl: 'Gaat deze bus naar het vliegveld?', thema: 'de weg vragen' },
  { es: 'Me he perdido, ¿me puede ayudar?', nl: 'Ik ben verdwaald, kunt u mij helpen?', thema: 'de weg vragen' },
  { es: '¿Cuánto se tarda en llegar andando?', nl: 'Hoelang duurt het om er lopend te komen?', thema: 'de weg vragen' },
  { es: 'Está a dos calles, al lado de la iglesia.', nl: 'Het is twee straten verderop, naast de kerk.', thema: 'de weg vragen' },
  { es: 'Una mesa para dos, por favor.', nl: 'Een tafel voor twee, alstublieft.', thema: 'in het restaurant' },
  { es: '¿Me trae la carta, por favor?', nl: 'Kunt u mij het menu brengen, alstublieft?', thema: 'in het restaurant' },
  { es: '¿Qué me recomienda?', nl: 'Wat kunt u mij aanraden?', thema: 'in het restaurant' },
  { es: 'Para mí, el pollo con verduras.', nl: 'Voor mij de kip met groenten.', thema: 'in het restaurant' },
  { es: '¿Tienen algún plato vegetariano?', nl: 'Hebben jullie een vegetarisch gerecht?', thema: 'in het restaurant' },
  { es: 'Soy alérgico a los frutos secos.', nl: 'Ik ben allergisch voor noten.', thema: 'in het restaurant' },
  { es: 'La cuenta, por favor.', nl: 'De rekening, alstublieft.', thema: 'in het restaurant' },
  { es: '¿Puedo pagar con tarjeta?', nl: 'Kan ik met de kaart betalen?', thema: 'in het restaurant' },
  { es: 'Estaba todo buenísimo, muchas gracias.', nl: 'Het was allemaal heerlijk, hartelijk dank.', thema: 'in het restaurant' },
  { es: '¿Nos pone un poco más de pan?', nl: 'Kunt u ons wat meer brood brengen?', thema: 'in het restaurant' },
  { es: '¿Cuánto cuesta esto?', nl: 'Hoeveel kost dit?', thema: 'boodschappen & winkelen' },
  { es: '¿Tienen esta camiseta en otra talla?', nl: 'Hebben jullie dit T-shirt in een andere maat?', thema: 'boodschappen & winkelen' },
  { es: 'Solo estoy mirando, gracias.', nl: 'Ik kijk alleen even rond, dank u.', thema: 'boodschappen & winkelen' },
  { es: '¿Puedo probármelo?', nl: 'Mag ik het passen?', thema: 'boodschappen & winkelen' },
  { es: '¿Aceptan tarjeta de crédito?', nl: 'Accepteren jullie creditcards?', thema: 'boodschappen & winkelen' },
  { es: '¿Me hace un descuento?', nl: 'Kunt u mij korting geven?', thema: 'boodschappen & winkelen' },
  { es: 'Me llevo estos dos, por favor.', nl: 'Ik neem deze twee, alstublieft.', thema: 'boodschappen & winkelen' },
  { es: '¿Dónde están los probadores?', nl: 'Waar zijn de paskamers?', thema: 'boodschappen & winkelen' },
  { es: '¿Me da una bolsa, por favor?', nl: 'Kunt u mij een tasje geven, alstublieft?', thema: 'boodschappen & winkelen' },
  { es: '¿A qué hora cierran la tienda?', nl: 'Hoe laat sluit de winkel?', thema: 'boodschappen & winkelen' },
  { es: 'Tengo una reserva a nombre de García.', nl: 'Ik heb een reservering op naam van García.', thema: 'hotel & overnachten' },
  { es: '¿Tienen una habitación libre para esta noche?', nl: 'Hebben jullie een kamer vrij voor vannacht?', thema: 'hotel & overnachten' },
  { es: '¿El desayuno está incluido?', nl: 'Is het ontbijt inbegrepen?', thema: 'hotel & overnachten' },
  { es: '¿A qué hora hay que dejar la habitación?', nl: 'Hoe laat moeten we uitchecken?', thema: 'hotel & overnachten' },
  { es: 'El aire acondicionado no funciona.', nl: 'De airconditioning doet het niet.', thema: 'hotel & overnachten' },
  { es: '¿Tienen wifi gratis en las habitaciones?', nl: 'Hebben jullie gratis wifi op de kamers?', thema: 'hotel & overnachten' },
  { es: '¿Me puede dar otra toalla, por favor?', nl: 'Kunt u mij nog een handdoek geven, alstublieft?', thema: 'hotel & overnachten' },
  { es: '¿Puedo dejar las maletas aquí un rato?', nl: 'Mag ik mijn koffers hier even laten staan?', thema: 'hotel & overnachten' },
  { es: '¿Hay parking en el hotel?', nl: 'Is er parkeergelegenheid bij het hotel?', thema: 'hotel & overnachten' },
  { es: 'Quisiera quedarme una noche más.', nl: 'Ik zou graag nog een nacht blijven.', thema: 'hotel & overnachten' },
  { es: '¿Dónde puedo comprar un billete?', nl: 'Waar kan ik een kaartje kopen?', thema: 'openbaar vervoer' },
  { es: 'Un billete de ida y vuelta a Madrid, por favor.', nl: 'Een retourtje naar Madrid, alstublieft.', thema: 'openbaar vervoer' },
  { es: '¿A qué hora sale el próximo tren?', nl: 'Hoe laat vertrekt de volgende trein?', thema: 'openbaar vervoer' },
  { es: '¿De qué andén sale?', nl: 'Van welk perron vertrekt hij?', thema: 'openbaar vervoer' },
  { es: '¿Este tren para en Sevilla?', nl: 'Stopt deze trein in Sevilla?', thema: 'openbaar vervoer' },
  { es: '¿Cuántas paradas faltan?', nl: 'Hoeveel haltes zijn het nog?', thema: 'openbaar vervoer' },
  { es: '¿Tengo que hacer transbordo?', nl: 'Moet ik overstappen?', thema: 'openbaar vervoer' },
  { es: 'Perdone, creo que este es mi asiento.', nl: 'Pardon, ik geloof dat dit mijn stoel is.', thema: 'openbaar vervoer' },
  { es: '¿Me avisa cuando lleguemos a la parada?', nl: 'Kunt u mij waarschuwen als we bij de halte zijn?', thema: 'openbaar vervoer' },
  { es: 'El tren lleva media hora de retraso.', nl: 'De trein heeft een halfuur vertraging.', thema: 'openbaar vervoer' },
  { es: '¡Ayuda! Necesito un médico.', nl: 'Help! Ik heb een dokter nodig.', thema: 'noodgevallen & gezondheid' },
  { es: 'Llame a una ambulancia, por favor.', nl: 'Bel een ambulance, alstublieft.', thema: 'noodgevallen & gezondheid' },
  { es: 'Me encuentro mal, me duele la cabeza.', nl: 'Ik voel me niet goed, ik heb hoofdpijn.', thema: 'noodgevallen & gezondheid' },
  { es: '¿Dónde está la farmacia más cercana?', nl: 'Waar is de dichtstbijzijnde apotheek?', thema: 'noodgevallen & gezondheid' },
  { es: 'Me han robado la cartera.', nl: 'Mijn portemonnee is gestolen.', thema: 'noodgevallen & gezondheid' },
  { es: 'Necesito ir al hospital.', nl: 'Ik moet naar het ziekenhuis.', thema: 'noodgevallen & gezondheid' },
  { es: 'Tengo fiebre y me duele la garganta.', nl: 'Ik heb koorts en keelpijn.', thema: 'noodgevallen & gezondheid' },
  { es: '¿Tiene algo para el dolor de estómago?', nl: 'Heeft u iets tegen buikpijn?', thema: 'noodgevallen & gezondheid' },
  { es: 'He perdido mi pasaporte.', nl: 'Ik ben mijn paspoort kwijt.', thema: 'noodgevallen & gezondheid' },
  { es: 'Por favor, llame a la policía.', nl: 'Bel alstublieft de politie.', thema: 'noodgevallen & gezondheid' },
  { es: '¿Qué tiempo hace hoy?', nl: 'Wat voor weer is het vandaag?', thema: 'small talk & meningen' },
  { es: 'Me gusta mucho esta ciudad.', nl: 'Ik vind deze stad heel leuk.', thema: 'small talk & meningen' },
  { es: 'Creo que tienes razón.', nl: 'Ik denk dat je gelijk hebt.', thema: 'small talk & meningen' },
  { es: 'En mi opinión, la comida aquí es excelente.', nl: 'Volgens mij is het eten hier uitstekend.', thema: 'small talk & meningen' },
  { es: '¿Qué te parece este sitio?', nl: 'Wat vind je van deze plek?', thema: 'small talk & meningen' },
  { es: 'No estoy muy de acuerdo con eso.', nl: 'Daar ben ik het niet echt mee eens.', thema: 'small talk & meningen' },
  { es: '¿Has estado antes en España?', nl: 'Ben je eerder in Spanje geweest?', thema: 'small talk & meningen' },
  { es: 'La verdad es que estoy muy cansado.', nl: 'Eerlijk gezegd ben ik heel moe.', thema: 'small talk & meningen' },
  { es: '¡Qué buena idea!', nl: 'Wat een goed idee!', thema: 'small talk & meningen' },
  { es: 'A mí me da igual, decide tú.', nl: 'Mij maakt het niet uit, beslis jij maar.', thema: 'small talk & meningen' },
  { es: '¿Qué hora es?', nl: 'Hoe laat is het?', thema: 'tijd & afspraken' },
  { es: 'Son las tres y media.', nl: 'Het is half vier.', thema: 'tijd & afspraken' },
  { es: '¿A qué hora quedamos?', nl: 'Hoe laat spreken we af?', thema: 'tijd & afspraken' },
  { es: 'Nos vemos a las ocho delante del cine.', nl: 'We zien elkaar om acht uur voor de bioscoop.', thema: 'tijd & afspraken' },
  { es: 'Voy a llegar un poco tarde.', nl: 'Ik ga een beetje te laat komen.', thema: 'tijd & afspraken' },
  { es: '¿Estás libre mañana por la tarde?', nl: 'Ben je morgenmiddag vrij?', thema: 'tijd & afspraken' },
  { es: '¿Podemos quedar otro día?', nl: 'Kunnen we een andere dag afspreken?', thema: 'tijd & afspraken' },
  { es: 'Perdón por el retraso.', nl: 'Sorry voor de vertraging.', thema: 'tijd & afspraken' },
  { es: '¿A qué hora abren mañana?', nl: 'Hoe laat gaan ze morgen open?', thema: 'tijd & afspraken' },
  { es: 'Tengo una cita a las diez de la mañana.', nl: 'Ik heb een afspraak om tien uur \'s ochtends.', thema: 'tijd & afspraken' },
  { es: 'No pasa nada, no te preocupes.', nl: 'Het geeft niet, maak je geen zorgen.', thema: 'dagelijkse uitdrukkingen' },
  { es: '¡Qué va, para nada!', nl: 'Welnee, helemaal niet!', thema: 'dagelijkse uitdrukkingen' },
  { es: 'Vale, de acuerdo.', nl: 'Oké, afgesproken.', thema: 'dagelijkse uitdrukkingen' },
  { es: 'Lo siento mucho, fue sin querer.', nl: 'Het spijt me erg, het was per ongeluk.', thema: 'dagelijkse uitdrukkingen' },
  { es: '¿Me puedes echar una mano?', nl: 'Kun je me even helpen?', thema: 'dagelijkse uitdrukkingen' },
  { es: 'Poco a poco se va lejos.', nl: 'Beetje bij beetje kom je ver.', thema: 'dagelijkse uitdrukkingen' },
  { es: 'Tranquilo, tómate tu tiempo.', nl: 'Rustig maar, neem de tijd.', thema: 'dagelijkse uitdrukkingen' },
  { es: '¡Buen provecho!', nl: 'Eet smakelijk!', thema: 'dagelijkse uitdrukkingen' },
  { es: 'Más vale tarde que nunca.', nl: 'Beter laat dan nooit.', thema: 'dagelijkse uitdrukkingen' },
  { es: '¡Que te vaya bien!', nl: 'Het ga je goed!', thema: 'dagelijkse uitdrukkingen' },
]
