// Antwoordbod-scenario's (gecureerd): partner opent, wat bied jij?
// Handen als tekst per kleur (♠ ♥ ♦ ♣), hoog → laag.
export type AntwoordScenario = {
  opening: string
  hand: [string, string, string, string]
  hcp: number
  opties: string[]
  goed: number
  uitleg: string
}

export const ANTWOORD_SCENARIOS: AntwoordScenario[] = [
  {
    opening: '1♠',
    hand: ['V 8 4', 'H 7 3', 'B 8 6 2', '9 5 3'],
    hcp: 7,
    opties: ['2♠', '1SA', 'pas', '3♠'],
    goed: 0,
    uitleg: 'Met 6–9 punten en driekaart steun voor partners vijfkaart steun je gewoon: 2♠.',
  },
  {
    opening: '1♠',
    hand: ['8 4', 'V B 7 3', 'H 8 6 2', '9 5 3'],
    hcp: 6,
    opties: ['1SA', '2♥', 'pas', '2♠'],
    goed: 0,
    uitleg: 'Geen steun (maar twee schoppen) en 6–9 punten; een nieuwe kleur op 2-niveau belooft 10+ — dus 1SA als vangnet.',
  },
  {
    opening: '1♠',
    hand: ['H V 8 4', 'A 7 3', '8 6 2', '9 5 3'],
    hcp: 9,
    opties: ['3♠', '2♠', '4♠', '1SA'],
    goed: 1,
    uitleg: 'Vierkaart steun maar 9 punten: dat is nog gewoon 2♠ (6–9). Vanaf 10–11 bied je 3♠.',
  },
  {
    opening: '1♠',
    hand: ['A V 8 4', 'H 7 3', 'H 8 6 2', '9 5'],
    hcp: 13,
    opties: ['4♠', '2♠', '2♦', '3♠'],
    goed: 2,
    uitleg: 'Met 12+ punten eerst een nieuwe kleur op 2-niveau (2♦) — daarna kun je altijd nog naar de schoppenmanche.',
  },
  {
    opening: '1♥',
    hand: ['7 4', 'V 9 6 3', 'A 8 5 2', '8 6 3'],
    hcp: 6,
    opties: ['2♥', 'pas', '1SA', '2♦'],
    goed: 0,
    uitleg: 'Driekaart of langer mee in partners hartenkleur en 6–9 punten: steun met 2♥.',
  },
  {
    opening: '1♥',
    hand: ['A V 8 6 3', '7 4', 'H 8 5', '8 6 3'],
    hcp: 9,
    opties: ['1♠', '1SA', '2♠', 'pas'],
    goed: 0,
    uitleg: 'Een nieuwe kleur op 1-niveau (1♠) kan al vanaf 6 punten en toont je vijfkaart schoppen.',
  },
  {
    opening: '1♥',
    hand: ['8 3', '7 4', 'V 8 5 2', 'B 7 6 3 2'],
    hcp: 3,
    opties: ['pas', '1SA', '2♣', '2♥'],
    goed: 0,
    uitleg: 'Met 0–5 punten pas je op elke opening van partner.',
  },
  {
    opening: '1♣',
    hand: ['V 8 6 3', 'A 7 4 2', '8 5', '9 6 3'],
    hcp: 6,
    opties: ['1♥', '1♠', '1SA', 'pas'],
    goed: 0,
    uitleg: 'Nieuwe kleuren "van onderaf": met twee vierkaarten bied je de laagste eerst — 1♥.',
  },
  {
    opening: '1♦',
    hand: ['H B 8 6 3', '7 4', 'V 5 2', '9 6 3'],
    hcp: 7,
    opties: ['1♠', '2♦', '1SA', 'pas'],
    goed: 0,
    uitleg: 'Een vijfkaart schoppen eerst laten zien: 1♠ (6+ punten volstaat op 1-niveau).',
  },
  {
    opening: '1SA',
    hand: ['V 8 4', 'H 7 3', 'B 8 6 2', '9 5 3'],
    hcp: 7,
    opties: ['pas', '2SA', '3SA', '2♦'],
    goed: 0,
    uitleg: 'Partner heeft 15–17. Met 0–7 punten en een vlakke hand: pas — samen te weinig voor de manche.',
  },
  {
    opening: '1SA',
    hand: ['V 8 4', 'H 7 3', 'A 8 6 2', '9 5 3'],
    hcp: 9,
    opties: ['2SA', 'pas', '3SA', '2♣'],
    goed: 0,
    uitleg: 'Met 8–9 punten nodig je uit met 2SA: partner past met 15 en biedt 3SA met 16–17.',
  },
  {
    opening: '1SA',
    hand: ['V 8 4', 'H 7 3', 'A 8 6 2', 'H 5 3'],
    hcp: 12,
    opties: ['3SA', '2SA', 'pas', '2♦'],
    goed: 0,
    uitleg: 'Met 10+ punten en geen lange hoge kleur bied je meteen de manche: 3SA (samen minstens 25).',
  },
  {
    opening: '1♥',
    hand: ['V 8', 'H B 6 3', 'A 8 6 2', '9 5 3'],
    hcp: 11,
    opties: ['3♥', '2♥', '4♥', '1SA'],
    goed: 0,
    uitleg: 'Vierkaart steun en 10–11 punten: inviteer met 3♥; partner biedt met extra\'s de manche 4♥.',
  },
  {
    opening: '1♠',
    hand: ['H V 8 4', 'A 7 3', 'H 8 6', '9 5 3'],
    hcp: 13,
    opties: ['4♠', '2♠', '3♠', '2♣'],
    goed: 0,
    uitleg: 'Vierkaart steun en 12+ punten: samen genoeg voor de manche — bied 4♠ (of eerst een nieuwe kleur; direct 4♠ is hier prima).',
  },

  // ─── 1♣-opening: reacties ───────────────────────────────────

  {
    opening: '1♣',
    hand: ['8 7 3', 'B 6 4', '9 7 5 2', '8 6 3'],
    hcp: 1,
    opties: ['pas', '1♦', '1SA', '2♣'],
    goed: 0,
    uitleg: 'Met slechts 1 punt pas je altijd — veel te weinig om te reageren.',
  },
  {
    opening: '1♣',
    hand: ['H 9 7 5 3', 'B 6 4', '8 5', '9 6 3'],
    hcp: 5,
    opties: ['1♠', 'pas', '1SA', '2♣'],
    goed: 0,
    uitleg: 'Vijfkaart schoppen en 5 punten: op 1-niveau mag je al vanaf 6 reageren, maar met precies 5 en een vijfkaart major is 1♠ nog net acceptabel.',
  },
  {
    opening: '1♣',
    hand: ['A 8 6', 'H 9 7 5', 'V 6 4 2', '8 3'],
    hcp: 10,
    opties: ['1♥', '1♦', '1SA', '2♣'],
    goed: 0,
    uitleg: 'Met twee vierkaarten bied je van onderaf — harten vóór ruiten. 1♥ toont je vierkaart en 6+ punten.',
  },
  {
    opening: '1♣',
    hand: ['A V 8', 'H 7 3', 'H B 6 2', 'V 5 3'],
    hcp: 15,
    opties: ['2SA', '3SA', '1♦', '2♣'],
    goed: 0,
    uitleg: 'Met 15–17 punten, vlakke verdeling en stoppers overal bied je 2SA — dat is invitationeel naar de manche.',
  },
  {
    opening: '1♣',
    hand: ['H V 8 6', '9 7 4 2', 'A 5', 'B 6 3'],
    hcp: 10,
    opties: ['1♥', '1♠', '2♣', '1SA'],
    goed: 0,
    uitleg: 'Twee vierkaarten majeur: bied de laagste eerst (1♥). Partner kan dan alsnog 1♠ bieden.',
  },

  // ─── 1♦-opening: reacties ──────────────────────────────────

  {
    opening: '1♦',
    hand: ['9 7 3', '8 6 4 2', 'V 5 3', '8 6 3'],
    hcp: 2,
    opties: ['pas', '1♥', '2♦', '1SA'],
    goed: 0,
    uitleg: 'Met 2 punten pas je — zelfs met steun voor ruiten heb je te weinig.',
  },
  {
    opening: '1♦',
    hand: ['A V 8 6', 'H 9 7 5', '8 3', '9 6 2'],
    hcp: 10,
    opties: ['1♥', '1♠', '1SA', '2♦'],
    goed: 0,
    uitleg: 'Twee vierkaarten majeur: bied de laagste eerst — 1♥. Partner kan daarna 1♠ bieden als hij die heeft.',
  },
  {
    opening: '1♦',
    hand: ['8 6 3', '9 7', 'A V 8 5 2', 'H 6 3'],
    hcp: 10,
    opties: ['3♦', '2♦', '1SA', 'pas'],
    goed: 0,
    uitleg: 'Vijfkaart steun en 10–11 punten: spring naar 3♦ om te inviteren. 2♦ zou maar 6–9 beloven.',
  },
  {
    opening: '1♦',
    hand: ['A 9 7', 'H V 6', 'B 8 4', 'H 9 5 3'],
    hcp: 13,
    opties: ['2♣', '3SA', '1SA', '2♦'],
    goed: 0,
    uitleg: 'Met 12+ punten en een vierkaart klaveren bied je een nieuwe kleur op 2-niveau (2♣) — dat is forcing.',
  },
  {
    opening: '1♦',
    hand: ['H 8 6 3', '9 7 4', 'V 5 2', 'B 6 3'],
    hcp: 7,
    opties: ['1♠', '2♦', '1SA', 'pas'],
    goed: 0,
    uitleg: 'Met een vierkaart schoppen en 6+ punten laat je die eerst zien op 1-niveau: 1♠.',
  },

  // ─── 1♥-opening: extra reacties ────────────────────────────

  {
    opening: '1♥',
    hand: ['A H 8 6', 'V 7 3', 'B 5 2', '9 6 3'],
    hcp: 11,
    opties: ['3♥', '2♥', '1♠', '4♥'],
    goed: 0,
    uitleg: 'Driekaart steun en 10–11 punten: inviteer met 3♥. Partner beslist met extra waarden over 4♥.',
  },
  {
    opening: '1♥',
    hand: ['H V 9 7 5', '6 3', 'A 8 4', '9 6 2'],
    hcp: 9,
    opties: ['1♠', '1SA', '2♥', 'pas'],
    goed: 0,
    uitleg: 'Geen hartensteun maar wel een vijfkaart schoppen: bied 1♠ (nieuwe kleur op 1-niveau, 6+ punten).',
  },
  {
    opening: '1♥',
    hand: ['A 8', 'H V 9 6 3', 'B 7 2', '9 5 3'],
    hcp: 11,
    opties: ['3♥', '4♥', '2♥', '2♦'],
    goed: 0,
    uitleg: 'Vijfkaart steun en 10–11 punten: spring naar 3♥ als invitatie. Partner past met minimum of biedt 4♥ met extra.',
  },
  {
    opening: '1♥',
    hand: ['9 7', 'A H 8 4', 'H V 6 2', 'V 5 3'],
    hcp: 14,
    opties: ['4♥', '3♥', '2♦', '3SA'],
    goed: 0,
    uitleg: 'Vierkaart steun en 13+ punten: samen genoeg voor manche — bied direct 4♥.',
  },
  {
    opening: '1♥',
    hand: ['9 7 5', '6 3', 'A H 8 6 2', 'V 5 3'],
    hcp: 10,
    opties: ['2♦', '1SA', '2♥', 'pas'],
    goed: 0,
    uitleg: 'Geen hartensteun, 10+ punten: een nieuwe kleur op 2-niveau (2♦) is forcing en toont je vijfkaart.',
  },

  // ─── 1♠-opening: extra reacties ────────────────────────────

  {
    opening: '1♠',
    hand: ['7 3', '9 6 4 2', 'B 8 5 3', '8 6 4'],
    hcp: 1,
    opties: ['pas', '1SA', '2♠', '2♥'],
    goed: 0,
    uitleg: 'Met 0–5 punten altijd passen — ook als je een andere vierkaart hebt.',
  },
  {
    opening: '1♠',
    hand: ['A 9 7 3', 'H 6', 'V B 5 2', '9 6 3'],
    hcp: 11,
    opties: ['3♠', '2♠', '4♠', '2♦'],
    goed: 0,
    uitleg: 'Vierkaart steun en 10–11 punten: spring naar 3♠ als invitatie richting manche.',
  },
  {
    opening: '1♠',
    hand: ['9 8', 'A H V 8 6', '9 7 3', 'B 6 2'],
    hcp: 11,
    opties: ['2♥', '1SA', '2♠', 'pas'],
    goed: 0,
    uitleg: 'Geen schoppensteun, 10+ punten en een vijfkaart harten: bied 2♥ — nieuwe kleur op 2-niveau is forcing.',
  },
  {
    opening: '1♠',
    hand: ['H 6 3', 'A V 9 5', '8 7 2', 'B 6 3'],
    hcp: 10,
    opties: ['2♠', '3♠', '2♥', '1SA'],
    goed: 0,
    uitleg: 'Driekaart steun en 10 punten: met driekaart steun en 10+ bij je gewoon 2♠ en daarna eventueel door naar manche. Sommige spelers zouden hier 3♠ bieden, maar 2♠ met driekaart is standaard.',
  },

  // ─── 1SA-opening: Stayman ──────────────────────────────────

  {
    opening: '1SA',
    hand: ['H 9 7 5', 'A 8 6 3', '9 5 2', '8 6'],
    hcp: 8,
    opties: ['2♣', '2SA', 'pas', '3SA'],
    goed: 0,
    uitleg: 'Twee vierkaarten majeur en 8+ punten: bied 2♣ (Stayman) om een 4-4 fit in harten of schoppen te vinden.',
  },
  {
    opening: '1SA',
    hand: ['A V 8 6', 'H 9 7 5', 'B 4 2', '8 3'],
    hcp: 11,
    opties: ['2♣', '3SA', '2SA', 'pas'],
    goed: 0,
    uitleg: 'Twee vierkaarten majeur en 10+ punten: Stayman (2♣). Als partner een major noemt, bied je de manche in die kleur.',
  },
  {
    opening: '1SA',
    hand: ['H 9 7 5', '8 6 3', 'A V 4', '9 5 2'],
    hcp: 10,
    opties: ['2♣', '3SA', 'pas', '2♠'],
    goed: 0,
    uitleg: 'Vierkaart schoppen en 10+ punten: probeer Stayman (2♣). Bij 2♠ van partner bied je 4♠; anders 3SA.',
  },
  {
    opening: '1SA',
    hand: ['V 9 6 3', 'H 8 7 5', '9 5 2', 'B 6'],
    hcp: 7,
    opties: ['2♣', 'pas', '2SA', '3♥'],
    goed: 0,
    uitleg: 'Stayman mag ook met 7–8 punten als je twee vierkaarten majeur hebt — je kunt altijd nog passen op 2♦.',
  },

  // ─── 1SA-opening: Jacoby-transfers ─────────────────────────

  {
    opening: '1SA',
    hand: ['8 6', 'H V 9 7 5 3', 'B 4 2', '9 3'],
    hcp: 7,
    opties: ['2♦', 'pas', '2♥', '3♥'],
    goed: 0,
    uitleg: 'Vijfkaart of langer harten: bied 2♦ als Jacoby-transfer. Partner biedt verplicht 2♥ en jij past daarna met zwakke hand.',
  },
  {
    opening: '1SA',
    hand: ['A H 9 7 5 3', '8 6', 'V 4 2', '9 3'],
    hcp: 10,
    opties: ['2♥', '2♠', '3♠', '3SA'],
    goed: 0,
    uitleg: 'Vijf+ schoppen: bied 2♥ als Jacoby-transfer. Partner biedt 2♠; met 10 punten bied je daarna 3SA (keuze).',
  },
  {
    opening: '1SA',
    hand: ['9 3', 'A V 8 7 6 2', 'H 5', 'B 4 3'],
    hcp: 11,
    opties: ['2♦', '3♥', '4♥', '2♣'],
    goed: 0,
    uitleg: 'Zeskaart harten en 11 punten: transfer met 2♦, daarna 4♥ bieden — samen minstens 25 punten.',
  },
  {
    opening: '1SA',
    hand: ['H V B 8 6 3', '9 7', 'A 5', '8 6 2'],
    hcp: 10,
    opties: ['2♥', '3♠', '2♣', '4♠'],
    goed: 0,
    uitleg: 'Zeskaart schoppen: transfer met 2♥ (partner biedt 2♠), daarna 3SA of 4♠ met de extra punten.',
  },
  {
    opening: '1SA',
    hand: ['9 5', 'H B 8 7 5', '8 6 3 2', 'V 3'],
    hcp: 6,
    opties: ['2♦', 'pas', '2♥', '2♣'],
    goed: 0,
    uitleg: 'Vijfkaart harten en 6 punten: Jacoby-transfer (2♦). Na partners 2♥ pas je — beter in een troefcontract dan in 1SA.',
  },

  // ─── 2♣-opening (sterk): reacties ─────────────────────────

  {
    opening: '2♣',
    hand: ['9 7 3', '8 6 4 2', 'V 8 5', '9 6 3'],
    hcp: 2,
    opties: ['2♦', 'pas', '2♥', '2SA'],
    goed: 0,
    uitleg: '2♣ is sterk en forcing: je mag NOOIT passen! Met 0–7 punten bied je het wachtbod 2♦.',
  },
  {
    opening: '2♣',
    hand: ['A V 8 5', '9 6 3', 'H 7 4', '8 6 2'],
    hcp: 10,
    opties: ['2♠', '2♦', '3♠', '3SA'],
    goed: 0,
    uitleg: 'Met 8+ punten en een goede vijfkaart bied je die direct (positieve reactie). Hier: 2♠ met A V.',
  },
  {
    opening: '2♣',
    hand: ['8 6 3', 'A H 9 7 5', 'V 4 2', '9 3'],
    hcp: 10,
    opties: ['2♥', '2♦', '3♥', '2SA'],
    goed: 0,
    uitleg: 'Goede vijfkaart harten (A H) en 8+ punten: bied direct 2♥ als positieve reactie op de sterke 2♣.',
  },
  {
    opening: '2♣',
    hand: ['H 9 5', 'V 8 6', 'A 7 4 3', 'B 6 2'],
    hcp: 11,
    opties: ['2SA', '2♦', '3SA', '3♦'],
    goed: 0,
    uitleg: 'Met 8+ punten maar geen vijfkaart: bied 2SA (positieve reactie, vlakke hand). Laat opener zijn kleur tonen.',
  },
  {
    opening: '2♣',
    hand: ['B 7 3', '9 6 4 2', '8 5 3', '8 6 4'],
    hcp: 1,
    opties: ['2♦', 'pas', '2SA', '3♣'],
    goed: 0,
    uitleg: 'Op 2♣ mag je nooit passen — het is absoluut forcing. Met slechts 1 punt: wachtbod 2♦.',
  },

  // ─── 2SA-opening: reacties ─────────────────────────────────

  {
    opening: '2SA',
    hand: ['9 7 3', '8 6 4', 'V 8 5 2', '9 6 3'],
    hcp: 2,
    opties: ['pas', '3♣', '3SA', '3♦'],
    goed: 0,
    uitleg: 'Partner heeft 20–22 punten. Met 2 punten: samen maximaal 24 — te weinig voor 3SA, dus pas.',
  },
  {
    opening: '2SA',
    hand: ['H 9 7 5', 'A 8 6 3', '9 5 2', '8 6'],
    hcp: 8,
    opties: ['3♣', '3SA', 'pas', '4SA'],
    goed: 0,
    uitleg: 'Twee vierkaarten majeur en 4+ punten: Stayman (3♣ over 2SA) om een 4-4 fit te zoeken.',
  },
  {
    opening: '2SA',
    hand: ['9 5', 'H V 8 7 5 3', '8 6', 'B 4 3'],
    hcp: 7,
    opties: ['3♦', '4♥', 'pas', '3♥'],
    goed: 0,
    uitleg: 'Vijf+ harten: Jacoby-transfer — over 2SA is dat 3♦ (één stap onder harten). Partner biedt 3♥.',
  },
  {
    opening: '2SA',
    hand: ['A 9 5', 'V 8 6', 'H 7 3', 'B 6 4 2'],
    hcp: 11,
    opties: ['3SA', '4SA', 'pas', '3♣'],
    goed: 0,
    uitleg: 'Vlakke hand en 4+ punten: samen minstens 25 — bied direct 3SA. Geen reden voor Stayman zonder vierkaart majeur.',
  },
  {
    opening: '2SA',
    hand: ['H 8 7 6 5 2', '9 3', 'V 6', 'B 4 3'],
    hcp: 7,
    opties: ['3♥', '3♠', '4♠', 'pas'],
    goed: 0,
    uitleg: 'Vijf+ schoppen: Jacoby-transfer — over 2SA is dat 3♥ (één stap onder schoppen). Partner biedt 3♠.',
  },

  // ─── Preemptieve openingen: reacties ───────────────────────

  {
    opening: '2♥',
    hand: ['A V 8', 'H 7 3', 'A B 6 2', '9 5 3'],
    hcp: 14,
    opties: ['4♥', '3♥', '2SA', '3SA'],
    goed: 0,
    uitleg: 'Partner opent zwak (2♥ = 6-kaart, 6–10 punten). Met driekaart steun en 14 punten: bied direct 4♥.',
  },
  {
    opening: '2♥',
    hand: ['H V 8 6', '9 3', 'A B 7 4', 'V 6 3'],
    hcp: 13,
    opties: ['2SA', '3♥', '3SA', 'pas'],
    goed: 0,
    uitleg: 'Geen hartensteun maar 13+ punten en stoppers: bied 2SA (16–18 in speelpunten), forcing voor één ronde.',
  },
  {
    opening: '2♥',
    hand: ['B 7 3', '9 6', '8 5 4 2', 'V 8 6 3'],
    hcp: 3,
    opties: ['pas', '3♥', '2SA', '4♥'],
    goed: 0,
    uitleg: 'Partner opent zwak — met slechts 3 punten en geen steun: pas. Je hebt samen te weinig.',
  },
  {
    opening: '2♠',
    hand: ['H 7 3', 'A V 8', 'A B 6 2', '9 5 3'],
    hcp: 14,
    opties: ['4♠', '3♠', '2SA', '3SA'],
    goed: 0,
    uitleg: 'Driekaart steun voor partners zwakke-twee schoppen en 14 punten: direct 4♠ bieden.',
  },
  {
    opening: '2♠',
    hand: ['9 3', 'A H 8 6', 'H V 7 4', 'V 6 3'],
    hcp: 14,
    opties: ['2SA', '3♠', 'pas', '3♥'],
    goed: 0,
    uitleg: 'Geen schoppensteun, 14+ punten: 2SA is het forcing enquêtebod. Partner beschrijft zijn hand nader.',
  },
  {
    opening: '3♣',
    hand: ['A V 8', 'H 9 7 3', 'A B 6', '9 5 3'],
    hcp: 14,
    opties: ['3SA', '4♣', '5♣', 'pas'],
    goed: 0,
    uitleg: 'Partner opent met een preemptieve 3♣. Met 14+ punten en stoppers in alle zijkleuren: bied 3SA.',
  },
  {
    opening: '3♦',
    hand: ['A 9 7', 'H V 8', 'B 6 3', 'A 9 5 3'],
    hcp: 15,
    opties: ['3SA', '4♦', '5♦', 'pas'],
    goed: 0,
    uitleg: 'Partner opent zwak met 3♦. Met stoppers en 15 punten: bied 3SA. Je verwacht 9 slagen.',
  },
  {
    opening: '3♥',
    hand: ['A H V 8', '6 3', 'H 9 7 5', 'V 6 2'],
    hcp: 15,
    opties: ['3♠', '4♥', '3SA', 'pas'],
    goed: 0,
    uitleg: 'Geen hartensteun maar eigen goede schoppen: bied 3♠ als eigen kleur. Toont vijfkaart en 14+ punten.',
  },

  // ─── Extra 1SA: vlakke sterke handen ───────────────────────

  {
    opening: '1SA',
    hand: ['A H 8', 'V 9 7', 'H B 6 2', 'V 5 3'],
    hcp: 16,
    opties: ['6SA', '4SA', '3SA', '2♣'],
    goed: 2,
    uitleg: 'Met 16 punten en vlakke hand: samen 31–33. Dat is net niet genoeg voor 6SA (33+ nodig). Bied gewoon 3SA.',
  },
  {
    opening: '1SA',
    hand: ['A H 9', 'A V 8', 'H V 6 2', 'B 5 3'],
    hcp: 19,
    opties: ['4SA', '6SA', '3SA', '2♣'],
    goed: 0,
    uitleg: 'Met 19 punten: samen 34–36. Bied 4SA — dat is een kwantitatieve invitatie naar 6SA, geen Blackwood.',
  },

  // ─── 1♣/1♦-opening: langekleurreacties ────────────────────

  {
    opening: '1♣',
    hand: ['A H B 8 6 3', '9 7', 'H 5 2', '8 6'],
    hcp: 12,
    opties: ['1♠', '2♠', '2♣', '3♠'],
    goed: 0,
    uitleg: 'Met een zeskaart schoppen en 12 punten: bied eerst 1♠ (op 1-niveau). Springbod is niet nodig — je kunt later doorbieden.',
  },
  {
    opening: '1♦',
    hand: ['9 5', 'A V 8 7 6 3', 'H 4 2', '8 6'],
    hcp: 10,
    opties: ['1♥', '2♥', '2♦', '3♥'],
    goed: 0,
    uitleg: 'Zeskaart harten en 10 punten: op 1-niveau is 1♥ voldoende. Een springbod (2♥) zou 16+ beloven.',
  },

  // ─── Gemengde situaties ────────────────────────────────────

  {
    opening: '1♥',
    hand: ['H B 8 6', 'A V', 'H 9 7 5', 'B 4 2'],
    hcp: 15,
    opties: ['2♦', '4♥', '1♠', '3SA'],
    goed: 2,
    uitleg: 'Met 15 punten en een vierkaart schoppen: bied eerst 1♠ (nieuwe kleur op 1-niveau). Met tweekaartensteun harten is dit nog te vroeg voor 4♥.',
  },
  {
    opening: '1♣',
    hand: ['H B 7', 'V 9 6', 'A 8 5 3', 'B 4 2'],
    hcp: 12,
    opties: ['1♦', '2♣', '1SA', '2SA'],
    goed: 0,
    uitleg: 'Met 12 punten en een vierkaart ruiten: bied 1♦. Nieuwe kleur op 1-niveau is forcing en kost niets.',
  },
  {
    opening: '1♠',
    hand: ['6 3', 'A H 9 5', 'V B 7 4', 'H 8 2'],
    hcp: 13,
    opties: ['2♥', '1SA', '2♠', '3SA'],
    goed: 0,
    uitleg: 'Geen schoppensteun, 13+ punten: bied 2♥ (nieuwe kleur op 2-niveau = forcing, 10+ punten).',
  },
  {
    opening: '1♦',
    hand: ['8 6 3', 'H 7 4', 'V B 9 5', '8 6 2'],
    hcp: 6,
    opties: ['2♦', '1SA', 'pas', '1♥'],
    goed: 0,
    uitleg: 'Met vierkaart steun in ruiten en 6–9 punten: steun met 2♦. Eenvoudige verhogingssituatie.',
  },
  {
    opening: '1♣',
    hand: ['A 9 7 5', '8 6 3', 'H V 4', 'B 6 2'],
    hcp: 11,
    opties: ['1♠', '1SA', '2♣', '2♦'],
    goed: 0,
    uitleg: 'Vierkaart schoppen en 11 punten: bied 1♠ om je major te tonen. Op 1-niveau altijd de major eerst.',
  },
  {
    opening: '1♥',
    hand: ['A V 8 6 3', 'H 4', 'B 9 7', 'V 6 3'],
    hcp: 12,
    opties: ['1♠', '2♠', '2♥', '3♥'],
    goed: 0,
    uitleg: 'Vijfkaart schoppen en 12 punten: bied 1♠ (nieuwe kleur op 1-niveau). Je kunt later schoppen herhalen.',
  },
  {
    opening: '1♠',
    hand: ['H V B 9 3', 'A 6', 'H 8 4', 'V 7 2'],
    hcp: 15,
    opties: ['4♠', '3♠', '2♦', '2SA'],
    goed: 0,
    uitleg: 'Vijfkaart steun en 15 punten: meer dan genoeg voor manche — bied direct 4♠.',
  },

  // ─── Meer 2♣-sterk: variaties ─────────────────────────────

  {
    opening: '2♣',
    hand: ['H 8 6 3', '9 5', 'A V 7 4 2', '8 6'],
    hcp: 10,
    opties: ['2♦', '2♠', '3♦', '2SA'],
    goed: 0,
    uitleg: 'Met 8+ punten en een vijfkaart ruiten zou je 3♦ kunnen bieden, maar de kwaliteit is matig. Wacht met 2♦ en beschrijf later.',
  },

  // ─── Preemptief: eigen preemptieve reacties ────────────────

  {
    opening: '1♠',
    hand: ['H 9 7 5 3', 'V 6', '8 5 3', 'B 6 2'],
    hcp: 7,
    opties: ['2♠', '3♠', '1SA', 'pas'],
    goed: 0,
    uitleg: 'Vijfkaart steun en 7 punten: dat is een gewone verhoging naar 2♠ (6–9 punten).',
  },
  {
    opening: '1♥',
    hand: ['8 4', 'H V 9 6 3', '7 5 2', 'B 6 3'],
    hcp: 7,
    opties: ['2♥', '3♥', '4♥', 'pas'],
    goed: 0,
    uitleg: 'Vijfkaart steun en 7 punten: eenvoudige verhoging naar 2♥. Sprongsteun (3♥) zou 10–11 beloven.',
  },
  {
    opening: '1♠',
    hand: ['H 8 6 5 3', '9', 'V 7 5 4 2', '8 6'],
    hcp: 5,
    opties: ['3♠', '2♠', '4♠', 'pas'],
    goed: 0,
    uitleg: 'Vijfkaart steun, singleton en weinig punten: spring naar 3♠ als preemptieve verhoging (zwak met veel troeven).',
  },
  {
    opening: '1♥',
    hand: ['8', 'H 9 7 6 5 3', '8 5 4 2', '6 3'],
    hcp: 3,
    opties: ['4♥', '3♥', '2♥', 'pas'],
    goed: 0,
    uitleg: 'Zeskaart steun maar bijna geen punten: spring naar 4♥ als obstructiebod. Blokkeert de tegenstanders.',
  },
]
