// Alle vaarknopen van knots3d.com/nl/vaarknopen (namen en korte doelen;
// per knoop een link naar de 3D-animatie op knots3d).
export type VaarKnoop = { naam: string; doel: string; url: string }

export const VAARKNOPEN: VaarKnoop[] = [
  { naam: 'Aanmeerknoop', doel: 'Snel losneembare knoop om tijdelijk een boot af te meren of een dier vast te maken.', url: 'https://knots3d.com/nl/aanmeerknoop' },
  { naam: 'Achtknoop', doel: 'Eenvoudige stopperknoop die voorkomt dat het touw door een zekeringsapparaat of gat glipt.', url: 'https://knots3d.com/nl/achtknoop' },
  { naam: 'Adelborstknoop', doel: 'Verstelbare frictieknoop voor gebruik op lijnen onder spanning.', url: 'https://knots3d.com/nl/adelborstknoop' },
  { naam: 'Ashley-stopknoop', doel: 'Een dikke, stevige stopper aan het einde van een touw.', url: 'https://knots3d.com/nl/ashley-stopknoop' },
  { naam: 'Becket-steek', doel: 'Een touw aan een vast oog of lus bevestigen.', url: 'https://knots3d.com/nl/becket-steek-knoop' },
  { naam: 'Boomknoop', doel: 'Touw vastmaken aan een rondhout of giek bij parallelle of haakse belasting.', url: 'https://knots3d.com/nl/boomknoop' },
  { naam: 'Broach-steek', doel: 'Twee touwen verbinden met een compacte, niet-klemmende steek.', url: 'https://knots3d.com/nl/broach-steek-knoop' },
  { naam: 'Buikgordingstros', doel: 'Touw of koorden netjes opbergen en klitten voorkomen voor gemakkelijk hanteren.', url: 'https://knots3d.com/nl/buikgordingstros-knoop' },
  { naam: 'Buntlinesteek', doel: 'Veilige en compacte steek.', url: 'https://knots3d.com/nl/buntlinesteek-knoop' },
  { naam: 'Buntlinesteek met slip', doel: 'Veilige en compacte steek met snelontkoppeling.', url: 'https://knots3d.com/nl/buntlinesteek-met-slip-knoop' },
  { naam: 'Drievoudige schootsteek', doel: 'Twee touwen van verschillende diameter of materiaal veilig verbinden.', url: 'https://knots3d.com/nl/drievoudige-schootsteek-knoop' },
  { naam: 'Drieweg-schootsteek', doel: 'Drie touwen van verschillende of vergelijkbare grootte veilig verbinden.', url: 'https://knots3d.com/nl/drieweg-schootsteek-knoop' },
  { naam: 'Dubbele Simon (onder)', doel: 'Twee touwen van enigszins verschillende diameter of constructie verbinden.', url: 'https://knots3d.com/nl/dubbele-simon-onder-knoop' },
  { naam: 'Dubbele Simon (over)', doel: 'Twee touwen van enigszins verschillende diameter of constructie verbinden.', url: 'https://knots3d.com/nl/dubbele-simon-over-knoop' },
  { naam: 'Dubbele drakenlus', doel: 'Sterke, vaste eindlus die snel en eenvoudig te leggen is.', url: 'https://knots3d.com/nl/dubbele-drakenlus-knoop' },
  { naam: 'Dubbele overhandknoop', doel: 'Betrouwbare, dikke stopperknoop aan het einde van een touw.', url: 'https://knots3d.com/nl/dubbele-overhandknoop' },
  { naam: 'Dubbele schootsteek', doel: 'Twee touwen van verschillende diktes of materialen stevig verbinden.', url: 'https://knots3d.com/nl/dubbele-schootsteek-knoop' },
  { naam: 'EStar-stopknoop', doel: 'Dikke stopperknoop voor standaard- en high-modulustouw.', url: 'https://knots3d.com/nl/estar-stopknoop' },
  { naam: 'Eenvoudige Simon (onder)', doel: 'Touwen van verschillende diameter verbinden, vooral synthetische.', url: 'https://knots3d.com/nl/eenvoudige-simon-onder-knoop' },
  { naam: 'Eenvoudige Simon (over)', doel: 'Twee touwen verbinden, vooral glad synthetisch touwwerk.', url: 'https://knots3d.com/nl/eenvoudige-simon-over-knoop' },
  { naam: 'Galeisteek', doel: 'Veilige tijdelijke steek met een snel losneembare knevel.', url: 'https://knots3d.com/nl/galeisteek-knoop' },
  { naam: 'Grondlijnsteek', doel: 'Een touw stevig bevestigen aan een rondhout, stut of een groter touw.', url: 'https://knots3d.com/nl/grondlijnsteek-knoop' },
  { naam: 'Handdrukknoop', doel: 'Klemvaste, compacte manier om twee touwen te verbinden.', url: 'https://knots3d.com/nl/handdrukknoop' },
  { naam: 'IJsaapknoop', doel: 'Schuif- en grijpsteek om touw stevig aan gladde of taps toelopende voorwerpen te bevestigen.', url: 'https://knots3d.com/nl/ijsaapknoop' },
  { naam: 'Ingestoken schootsteek', doel: 'Touwen van verschillende of vergelijkbare grootte veilig verbinden.', url: 'https://knots3d.com/nl/ingestoken-schootsteek-knoop' },
  { naam: 'Karaaksteek', doel: 'Dik, stijf touw of kabel stevig verbinden.', url: 'https://knots3d.com/nl/karaaksteek-knoop' },
  { naam: 'Kikkerhaak', doel: 'Een touw vastmaken aan een kikker op een steiger of boot.', url: 'https://knots3d.com/nl/kikkerhaak-knoop' },
  { naam: 'Lopende paalsteek', doel: 'Strop voor het vastzetten of ophalen van objecten bij zeilen en boomwerk.', url: 'https://knots3d.com/nl/lopende-paalsteek-knoop' },
  { naam: 'Lossers-achteraanlegsteek', doel: 'Snelle, tijdelijke manier om een klein vaartuig aan een bolder vast te leggen.', url: 'https://knots3d.com/nl/lossers-achteraanlegsteek-knoop' },
  { naam: 'Mastworp (bocht)', doel: 'Een touw aan een paal bevestigen zonder toegang tot de uiteinden.', url: 'https://knots3d.com/nl/mastworp-bocht-knoop' },
  { naam: 'Mastworp (einde)', doel: 'Een touw aan een paal of rondhout vastzetten.', url: 'https://knots3d.com/nl/mastworp-einde-knoop' },
  { naam: 'Mastworp met geklemde rondtorn', doel: 'Veilige steek onder wisselende spanning, voor natuurlijke of synthetische touwen.', url: 'https://knots3d.com/nl/mastworp-met-geklemde-rondtorn-knoop' },
  { naam: 'Mastworp met slip', doel: 'Snelontkoppeling, tijdelijke bevestiging.', url: 'https://knots3d.com/nl/mastworp-met-slip-knoop' },
  { naam: 'Mastworp met voorslag', doel: 'Eenvoudige frictieknoop voor trek in de lengterichting langs een object.', url: 'https://knots3d.com/nl/mastworp-met-voorslag-knoop' },
  { naam: 'Meerpaalworp', doel: 'Snelle manier om een boot aan een aanlegpaal vast te maken.', url: 'https://knots3d.com/nl/meerpaalworp-knoop' },
  { naam: 'Meervoudige overhandknoop', doel: 'Stopknoop met extra windingen voor meer volume of voor decoratie.', url: 'https://knots3d.com/nl/meervoudige-overhandknoop' },
  { naam: 'Noodmastknoop', doel: 'Decoratieve knoop met drie lussen, basis voor een mat.', url: 'https://knots3d.com/nl/noodmastknoop' },
  { naam: 'Paalsteek', doel: 'Variant van de paalsteek met het tamp aan de buitenzijde.', url: 'https://knots3d.com/nl/paalsteek-knoop' },
  { naam: 'Paalsteek (2)', doel: 'Vrij veilige vaste lus aan het uiteinde van een touw.', url: 'https://knots3d.com/nl/paalsteek-2-knoop' },
  { naam: 'Paalsteek (snel)', doel: 'Snel te leggen, relatief veilige vaste lus.', url: 'https://knots3d.com/nl/paalsteek-snel-knoop' },
  { naam: 'Paalsteek in de bocht', doel: 'Veilige dubbele lus in het midden van een touw.', url: 'https://knots3d.com/nl/paalsteek-in-de-bocht-knoop' },
  { naam: 'Pedigree-koesteek', doel: 'Veiligere variant van de koesteek.', url: 'https://knots3d.com/nl/pedigree-koesteek-knoop' },
  { naam: 'Platte knoop', doel: 'Eenvoudige bindknoop voor het vastzetten van objecten, niet geschikt voor het verbinden van twee touwen.', url: 'https://knots3d.com/nl/platte-knoop' },
  { naam: 'Rondtorn met twee halve steken', doel: 'Veilige knoop om een touw aan een paal of ring vast te maken.', url: 'https://knots3d.com/nl/rondtorn-met-twee-halve-steken-knoop' },
  { naam: 'Schavotknoop', doel: 'Veilige knoop om een touw aan karabijnhaken of sluitingen te binden.', url: 'https://knots3d.com/nl/schavotknoop' },
  { naam: 'Schootsteek', doel: 'Touwen van verschillende of vergelijkbare grootte veilig verbinden.', url: 'https://knots3d.com/nl/schootsteek-knoop' },
  { naam: 'Seizingsteek', doel: 'Twee touwen van verschillende diameter verbinden.', url: 'https://knots3d.com/nl/seizingsteek-knoop' },
  { naam: 'Stierknoop (bocht)', doel: 'Een touw stevig bevestigen aan een paal, rondhout of ring.', url: 'https://knots3d.com/nl/stierknoop-bocht' },
  { naam: 'Stierknoop (einde)', doel: 'Een touw stevig bevestigen aan een rondhout, paal of ring.', url: 'https://knots3d.com/nl/stierknoop-einde' },
  { naam: 'Struikroverssteek', doel: 'Snelontkoppelknoop om een boot of dier tijdelijk aan een reling vast te zetten.', url: 'https://knots3d.com/nl/struikroverssteek-knoop' },
  { naam: 'Stuwadoorsknoop', doel: 'Middelgrote stopperknoop om te voorkomen dat een touw door een katrol glijdt.', url: 'https://knots3d.com/nl/stuwadoorsknoop' },
  { naam: 'Uli-knoop', doel: 'Een touweinde gewicht geven om over afstand te kunnen werpen.', url: 'https://knots3d.com/nl/uli-knoop' },
  { naam: 'Valknoop', doel: 'Een touw stevig bevestigen aan een sluiting of ring om te hijsen.', url: 'https://knots3d.com/nl/valknoop' },
  { naam: 'Vlaamse spiraal', doel: 'Touw in een platte spiraal opgerold voor nette, tijdelijke opslag op steigers.', url: 'https://knots3d.com/nl/vlaamse-spiraal-knoop' },
  { naam: 'Waterpaalsteek', doel: 'Veilige variant van de paalsteek voor gebruik in natte omstandigheden zonder vast te lopen.', url: 'https://knots3d.com/nl/waterpaalsteek-knoop' },
  { naam: 'Werpankersteek', doel: 'Een lijn aan een anker, ring of paal bevestigen.', url: 'https://knots3d.com/nl/werpankersteek-knoop' },
  { naam: 'Werplijnknoop', doel: 'Een touwuiteinde gewicht geven om over afstand te werpen.', url: 'https://knots3d.com/nl/werplijnknoop' },
  { naam: 'Zeemanstros', doel: 'Touw netjes opwinden en vastzetten voor opslag.', url: 'https://knots3d.com/nl/zeemanstros-knoop' },
]
