// Planten, bomen, struiken en bloemen die veel voorkomen in Nederland.

export type PlantType = 'Boom' | 'Struik' | 'Plant' | 'Bloem'

export type Plant = {
  naam: string
  latijn: string
  type: PlantType
  beschrijving: string
  kenmerk: string
  bloei: string
  emoji: string
}

export const FLORA: Plant[] = [
  { naam: 'Zomereik', latijn: 'Quercus robur', type: 'Boom', beschrijving: 'Herkenbaar aan de gelobde bladeren op korte steel en de eikels aan lange steeltjes; kan honderden jaren oud worden.', kenmerk: 'Belangrijkste inheemse boom voor biodiversiteit; huisvest honderden insectensoorten.', bloei: 'april–mei', emoji: '🌳' },
  { naam: 'Beuk', latijn: 'Fagus sylvatica', type: 'Boom', beschrijving: 'Gladde grijze bast en glanzende, golvend gerande bladeren; vruchtjes zijn driekantige beukennootjes.', kenmerk: 'Vormt dicht bladerdek waardoor er weinig onder groeit; populair als haag.', bloei: 'april–mei', emoji: '🌳' },
  { naam: 'Ruwe berk', latijn: 'Betula pendula', type: 'Boom', beschrijving: 'Opvallende witte bast met zwarte groeven en fijne, hangende twijgen met driehoekige bladeren.', kenmerk: 'Pioniersboom die snel kale grond kolonaliseert; zaad verspreidt met de wind.', bloei: 'april–mei', emoji: '🌳' },
  { naam: 'Schietwilg', latijn: 'Salix alba', type: 'Boom', beschrijving: 'Lange smalle zilvergrijze bladeren en soepele takken; vaak geknot langs water.', kenmerk: 'Groeit razendsnel en houdt van natte grond; typisch voor het Hollandse polderlandschap.', bloei: 'april', emoji: '🌳' },
  { naam: 'Zwarte els', latijn: 'Alnus glutinosa', type: 'Boom', beschrijving: 'Ronde, aan de top ingedeukte bladeren en kleine houtige \'elzenpropjes\' die de winter blijven hangen.', kenmerk: 'Bindt stikstof en groeit graag met natte voeten langs sloten en beken.', bloei: 'februari–maart', emoji: '🌳' },
  { naam: 'Gewone esdoorn', latijn: 'Acer pseudoplatanus', type: 'Boom', beschrijving: 'Grote handvormige bladeren met vijf lobben en gevleugelde zaden die als helikoptertjes ronddraaien.', kenmerk: 'Sterk en snelgroeiend; de draaiende zaden verspreiden zich ver van de boom.', bloei: 'april–mei', emoji: '🌳' },
  { naam: 'Zomerlinde', latijn: 'Tilia platyphyllos', type: 'Boom', beschrijving: 'Hartvormige bladeren en geurende gele bloemtrossen aan een schutblaadje; vaak als laanboom.', kenmerk: 'Bloemen zijn geliefd bij bijen en worden gebruikt voor lindebloesemthee.', bloei: 'juni–juli', emoji: '🌳' },
  { naam: 'Gewone es', latijn: 'Fraxinus excelsior', type: 'Boom', beschrijving: 'Geveerde bladeren met meerdere blaadjes en zwarte, fluweelachtige winterknoppen.', kenmerk: 'Bedreigd door de essentaksterfte, een agressieve schimmelziekte.', bloei: 'april', emoji: '🌳' },
  { naam: 'Grove den', latijn: 'Pinus sylvestris', type: 'Boom', beschrijving: 'Naalden in paren en een oranjebruine bast in de kroon; naaldboom van zandgronden.', kenmerk: 'Veel aangeplant op de Veluwe; kan goed tegen droge, arme zandgrond.', bloei: 'mei', emoji: '🌲' },
  { naam: 'Paardenkastanje', latijn: 'Aesculus hippocastanum', type: 'Boom', beschrijving: 'Grote handvormig samengestelde bladeren en witte bloemkaarsen; glanzende bruine kastanjes in stekelige bolsters.', kenmerk: 'Kinderen rapen de kastanjes; niet eetbaar voor mensen maar geliefd knutselmateriaal.', bloei: 'mei', emoji: '🌳' },
  { naam: 'Haagbeuk', latijn: 'Carpinus betulus', type: 'Boom', beschrijving: 'Lijkt op beuk maar met dubbel gezaagde, geribde bladeren; vaak als strakke haag geschoren.', kenmerk: 'Houdt in de winter zijn bruine blad vast, ideaal als wintergroene haag.', bloei: 'april–mei', emoji: '🌳' },
  { naam: 'Hazelaar', latijn: 'Corylus avellana', type: 'Struik', beschrijving: 'Ronde, ruw behaarde bladeren en gele hangende katjes vroeg in het jaar; levert hazelnoten.', kenmerk: 'Een van de vroegste bloeiers; de katjes stuiven al in februari.', bloei: 'februari–maart', emoji: '🌿' },
  { naam: 'Eenstijlige meidoorn', latijn: 'Crataegus monogyna', type: 'Struik', beschrijving: 'Doornige struik met diep ingesneden bladeren, witte bloemen en rode besjes (haagappels).', kenmerk: 'Veelgebruikt in landschapshagen; bessen en bloemen zijn waardevol voor vogels.', bloei: 'mei', emoji: '🌿' },
  { naam: 'Gewone vlier', latijn: 'Sambucus nigra', type: 'Struik', beschrijving: 'Geveerde bladeren, platte schermen met romige bloemen en later zwarte besjes.', kenmerk: 'Bloemen en bessen worden gebruikt voor siroop, limonade en gelei.', bloei: 'juni', emoji: '🌿' },
  { naam: 'Sleedoorn', latijn: 'Prunus spinosa', type: 'Struik', beschrijving: 'Sterk doornige struik die eerst wit bloeit en pas daarna in blad komt; blauwe bessen (sleepruimpjes).', kenmerk: 'De wrange bessen worden na de eerste nachtvorst gebruikt voor sloe gin.', bloei: 'maart–april', emoji: '🌿' },
  { naam: 'Hondsroos', latijn: 'Rosa canina', type: 'Struik', beschrijving: 'Klimmende wilde roos met haakvormige stekels, lichtroze bloemen en rode rozenbottels.', kenmerk: 'De rozenbottels zitten vol vitamine C en worden verwerkt tot thee en jam.', bloei: 'juni–juli', emoji: '🌹' },
  { naam: 'Gewone braam', latijn: 'Rubus fruticosus', type: 'Struik', beschrijving: 'Stekelige, boogvormig groeiende ranken met samengestelde bladeren en zwarte bramen.', kenmerk: 'Vormt ondoordringbare struwelen die veel dieren beschutting bieden.', bloei: 'juni–augustus', emoji: '🌿' },
  { naam: 'Duindoorn', latijn: 'Hippophae rhamnoides', type: 'Struik', beschrijving: 'Doornige struik met smalle zilvergrijze blaadjes en feloranje bessen; typisch voor de duinen.', kenmerk: 'Bessen zijn extreem rijk aan vitamine C; struik legt met wortels het duinzand vast.', bloei: 'april', emoji: '🌿' },
  { naam: 'Gewone hulst', latijn: 'Ilex aquifolium', type: 'Struik', beschrijving: 'Wintergroene struik met glanzende, stekelige bladeren en rode besjes; klassiek kerstgroen.', kenmerk: 'Alleen vrouwelijke planten dragen bessen; blad blijft het hele jaar groen.', bloei: 'mei–juni', emoji: '🌿' },
  { naam: 'Struikheide', latijn: 'Calluna vulgaris', type: 'Struik', beschrijving: 'Lage struik met kleine schubvormige blaadjes en talloze paarsroze bloempjes; kleurt heidevelden.', kenmerk: 'Kleurt eind augustus hele heidevelden paars; belangrijke drachtplant voor bijen.', bloei: 'augustus–september', emoji: '🌿' },
  { naam: 'Klimop', latijn: 'Hedera helix', type: 'Plant', beschrijving: 'Wintergroene klimplant met glanzende, vaak gelobde bladeren die met hechtwortels omhoog klimt.', kenmerk: 'Bloeit pas laat in het najaar en is dan een belangrijke laatste nectarbron voor insecten.', bloei: 'september–oktober', emoji: '🌿' },
  { naam: 'Grote brandnetel', latijn: 'Urtica dioica', type: 'Plant', beschrijving: 'Rechtopstaande plant met getande bladeren bedekt met brandharen die bij aanraking prikken.', kenmerk: 'Waardplant voor rupsen van dagpauwoog en atalanta; jonge blaadjes zijn eetbaar als soep.', bloei: 'juni–september', emoji: '🌿' },
  { naam: 'Fluitenkruid', latijn: 'Anthriscus sylvestris', type: 'Plant', beschrijving: 'Hoge schermbloem met fijn geveerde bladeren en witte bloemschermen die bermen wit kleuren.', kenmerk: 'Bloeit uitbundig in mei langs vrijwel elke Nederlandse wegberm.', bloei: 'april–juni', emoji: '🌿' },
  { naam: 'Speenkruid', latijn: 'Ficaria verna', type: 'Plant', beschrijving: 'Lage plant met glanzende hartvormige bladeren en glimmend gele stervormige bloemen.', kenmerk: 'Een van de eerste voorjaarsbloeiers; verdwijnt alweer boven de grond in de zomer.', bloei: 'maart–april', emoji: '🌼' },
  { naam: 'Grote lisdodde', latijn: 'Typha latifolia', type: 'Plant', beschrijving: 'Oeverplant met lange platte bladeren en de kenmerkende bruine \'sigaar\' als bloeiwijze.', kenmerk: 'De bruine sigaar bestaat uit duizenden zaadjes die als pluis wegwaaien.', bloei: 'juni–juli', emoji: '🌿' },
  { naam: 'Riet', latijn: 'Phragmites australis', type: 'Plant', beschrijving: 'Hoog grasachtig gewas met pluimen aan de top; vormt uitgestrekte rietvelden langs water.', kenmerk: 'Gebruikt als dakbedekking (rieten dak) en biedt broedplek aan rietvogels.', bloei: 'augustus–september', emoji: '🌿' },
  { naam: 'Gewone smeerwortel', latijn: 'Symphytum officinale', type: 'Plant', beschrijving: 'Ruw behaarde plant met grote spitse bladeren en hangende paarse of witte klokjesbloemen.', kenmerk: 'Van oudsher als geneeskruid gebruikt bij botbreuken, vandaar \'beenheler\'.', bloei: 'mei–juli', emoji: '🌿' },
  { naam: 'Klein hoefblad', latijn: 'Tussilago farfara', type: 'Plant', beschrijving: 'Gele bloemhoofdjes verschijnen op geschubde stengels vóór de grote hoefijzervormige bladeren.', kenmerk: 'Bloeit zeer vroeg op kale, vaak verstoorde grond nog voordat het blad komt.', bloei: 'maart–april', emoji: '🌼' },
  { naam: 'Echte kamille', latijn: 'Matricaria chamomilla', type: 'Plant', beschrijving: 'Fijn verdeelde blaadjes en madeliefachtige bloemen met een holle, geurende gele bodem.', kenmerk: 'Gedroogde bloemen leveren de bekende kalmerende kamillethee.', bloei: 'mei–augustus', emoji: '🌼' },
  { naam: 'Jakobskruiskruid', latijn: 'Jacobaea vulgaris', type: 'Plant', beschrijving: 'Hoge plant met gele bloemschermen en diep ingesneden bladeren; typisch in bermen en duinen.', kenmerk: 'Giftig voor vee, maar waardplant voor de opvallend gestreepte rups van de sint-jacobsvlinder.', bloei: 'juli–augustus', emoji: '🌼' },
  { naam: 'Grote weegbree', latijn: 'Plantago major', type: 'Plant', beschrijving: 'Rozet van brede, sterk generfde bladeren met een rechtopstaande groene bloeiaar.', kenmerk: 'Verdraagt betreding uitstekend en groeit daardoor midden op paadjes.', bloei: 'juni–september', emoji: '🌿' },
  { naam: 'Zevenblad', latijn: 'Aegopodium podagraria', type: 'Plant', beschrijving: 'Woekerende schermbloem met drietallig samengestelde bladeren en witte bloemschermpjes.', kenmerk: 'Berucht als hardnekkig tuinonkruid, maar de jonge blaadjes zijn eetbaar.', bloei: 'juni–juli', emoji: '🌿' },
  { naam: 'Paardenbloem', latijn: 'Taraxacum officinale', type: 'Bloem', beschrijving: 'Diepgele bloemhoofdjes op holle stengels met melksap; later de bekende witte pluizenbol.', kenmerk: 'De zaadpluizen waaien met de wind mee; vroege en rijke nectarbron voor bijen.', bloei: 'april–mei', emoji: '🌼' },
  { naam: 'Madeliefje', latijn: 'Bellis perennis', type: 'Bloem', beschrijving: 'Klein bloemetje met witte straalbloemen rond een geel hart, op korte steel in het gazon.', kenmerk: 'Sluit de bloem \'s avonds en bij regen; bloeit vrijwel het hele jaar door.', bloei: 'maart–oktober', emoji: '🌼' },
  { naam: 'Scherpe boterbloem', latijn: 'Ranunculus acris', type: 'Bloem', beschrijving: 'Glanzend gele bloemen met vijf blaadjes op vertakte stengels in vochtige weilanden.', kenmerk: 'De glimmende blaadjes weerkaatsen zonlicht; onder de kin houden \'verraadt\' of je van boter houdt.', bloei: 'mei–juli', emoji: '🌼' },
  { naam: 'Grote klaproos', latijn: 'Papaver rhoeas', type: 'Bloem', beschrijving: 'Felrode papierachtige bloembladen met zwarte vlek in het hart, op behaarde stengels.', kenmerk: 'Symbool van herdenking; kiemt massaal op omgewoelde grond en akkerranden.', bloei: 'juni–juli', emoji: '🌸' },
  { naam: 'Korenbloem', latijn: 'Centaurea cyanus', type: 'Bloem', beschrijving: 'Helderblauwe, gerafelde bloemhoofdjes op slanke grijsgroene stengels tussen graan.', kenmerk: 'Vroeger een akkeronkruid, nu vooral in bloemenmengsels vanwege de intens blauwe kleur.', bloei: 'juni–augustus', emoji: '🌸' },
  { naam: 'Gewone margriet', latijn: 'Leucanthemum vulgare', type: 'Bloem', beschrijving: 'Grote bloemen met witte straalbladen rond een geel hart op lange stengels in bermen.', kenmerk: 'Klassieke \'hij houdt van mij, hij houdt van mij niet\'-bloem.', bloei: 'mei–augustus', emoji: '🌼' },
  { naam: 'Sleutelbloem', latijn: 'Primula veris', type: 'Bloem', beschrijving: 'Rozet van gerimpelde bladeren met een scherm van hangende, dieper gele geurende bloemetjes.', kenmerk: 'Vroege lentebloeier; de oranje vlekjes in de keel leiden insecten naar de nectar.', bloei: 'april–mei', emoji: '🌼' },
  { naam: 'Sneeuwklokje', latijn: 'Galanthus nivalis', type: 'Bloem', beschrijving: 'Klein bolgewas met hangende witte klokjes met groene puntjes; komt door de winterbodem.', kenmerk: 'Een van de allereerste bloeiers, vaak al bloeiend door een laatste laagje sneeuw.', bloei: 'februari–maart', emoji: '🌸' },
  { naam: 'Bosanemoon', latijn: 'Anemone nemorosa', type: 'Bloem', beschrijving: 'Lage bosplant met diep ingesneden blad en witte, soms roze aangelopen sterbloemen.', kenmerk: 'Vormt in het voorjaar witte tapijten op de bosbodem vóór het bladerdek dichtgaat.', bloei: 'maart–april', emoji: '🌸' },
  { naam: 'Wilde narcis', latijn: 'Narcissus pseudonarcissus', type: 'Bloem', beschrijving: 'Geel bolgewas met een donkere trompet omringd door lichtere bloembladen.', kenmerk: 'Kondigt de lente aan; massaal aangeplant in parken en bermen.', bloei: 'maart–april', emoji: '🌼' },
  { naam: 'Tulp', latijn: 'Tulipa gesneriana', type: 'Bloem', beschrijving: 'Bolgewas met een rechte stengel en een enkele bekervormige bloem in tal van kleuren.', kenmerk: 'Hét symbool van Nederland; de bollenvelden trekken jaarlijks miljoenen bezoekers.', bloei: 'april–mei', emoji: '🌷' },
  { naam: 'Blauwe druifjes', latijn: 'Muscari botryoides', type: 'Bloem', beschrijving: 'Klein bolgewas met een tros van bolvormige blauwe bloempjes die op een druiventros lijken.', kenmerk: 'Verwildert makkelijk en vormt in het voorjaar blauwe stroken in tuinen en parken.', bloei: 'maart–april', emoji: '🌸' },
  { naam: 'Krokus', latijn: 'Crocus vernus', type: 'Bloem', beschrijving: 'Klein bolgewas met bekervormige paarse, witte of gele bloemen laag boven de grond.', kenmerk: 'Opent de bloem alleen in de zon; vroege nectarbron voor de eerste hommels.', bloei: 'februari–maart', emoji: '🌸' },
  { naam: 'Vergeet-mij-nietje', latijn: 'Myosotis arvensis', type: 'Bloem', beschrijving: 'Kleine hemelsblauwe bloempjes met geel hartje aan zich ontrollende bloeistengels.', kenmerk: 'Symbool van trouw en herinnering; zaait zichzelf rijkelijk uit in tuinen.', bloei: 'april–juni', emoji: '🌸' },
  { naam: 'Zonnebloem', latijn: 'Helianthus annuus', type: 'Bloem', beschrijving: 'Zeer hoge plant met een groot bloemhoofd van gele straalbladen rond een bruin zadenhart.', kenmerk: 'De jonge bloemknoppen draaien met de zon mee (heliotropisme).', bloei: 'juli–september', emoji: '🌻' },
  { naam: 'Boshyacint', latijn: 'Hyacinthoides non-scripta', type: 'Bloem', beschrijving: 'Bosplant met smalle bladeren en een overhangende tros geurende, klokvormige blauwe bloemen.', kenmerk: 'Vormt in oude bossen dichte blauwe tapijten; ook wel wilde hyacint genoemd.', bloei: 'april–mei', emoji: '🌸' },
  { naam: 'Pinksterbloem', latijn: 'Cardamine pratensis', type: 'Bloem', beschrijving: 'Slanke plant met geveerde blaadjes en lichtroze tot lila bloemen in vochtige weilanden.', kenmerk: 'Bloeit rond Pinksteren; waardplant voor het oranjetipje-vlindertje.', bloei: 'april–mei', emoji: '🌸' },
  { naam: 'Wilde hyacint', latijn: 'Hyacinthus orientalis', type: 'Bloem', beschrijving: 'Bolgewas met een stevige tros dichte, sterk geurende bloemen in paars, roze of wit.', kenmerk: 'Intens geurend voorjaarsbolgewas; veel geteeld in de Bollenstreek.', bloei: 'maart–april', emoji: '🌸' },
  { naam: 'Dotterbloem', latijn: 'Caltha palustris', type: 'Bloem', beschrijving: 'Moerasplant met glanzende ronde bladeren en grote, glimmend gele bloemen langs slootkanten.', kenmerk: 'Kleurt natte weilanden en slootranden goudgeel in het vroege voorjaar.', bloei: 'maart–mei', emoji: '🌼' },
  { naam: 'Zwarte nachtschade', latijn: 'Solanum nigrum', type: 'Plant', beschrijving: 'Vertakte plant met witte stervormige bloempjes en glanzende zwarte besjes.', kenmerk: 'De onrijpe besjes zijn giftig; familie van aardappel en tomaat.', bloei: 'juli–september', emoji: '🌿' },
  { naam: 'Gewone berenklauw', latijn: 'Heracleum sphondylium', type: 'Plant', beschrijving: 'Forse schermbloem met grote ruwe bladeren en brede witte bloemschermen in bermen.', kenmerk: 'Onschuldiger dan zijn reuzenneef, maar het sap kan bij zon lichte huidirritatie geven.', bloei: 'juni–september', emoji: '🌿' },
]
